import {createServer} from 'node:http';
import {decrypt,encrypt,identifierHash,normalizeIdentifier,otpauthUri,passwordRecord,parseCookies,publicError,randomCode,randomId,sessionCookie,sessionToken,sha256,codeHash,verifyPassword,newTotpSecret,verifyTotp} from './security.mjs';
import {analyzeToolPhoto,authorizePayment,sendVerification} from './providers.mjs';
import {creditsCents,openDb,profileFor,publicProfileIdByName,saveProfile,stateFor} from './db.mjs';

const PORT=Number(process.env.PORT||8787);
const ALLOWED_ORIGINS=(process.env.NG_ALLOWED_ORIGINS||'http://localhost:5173,http://127.0.0.1:5173,https://smkimbal.github.io').split(',').map(x=>x.trim()).filter(Boolean);
const SESSION_MS=7*24*60*60*1000, VERIFY_MS=10*60*1000, CHALLENGE_MS=5*60*1000;
const limits=new Map();

function cors(req,res){const origin=req.headers.origin;if(origin&&ALLOWED_ORIGINS.includes(origin)){res.setHeader('Access-Control-Allow-Origin',origin);res.setHeader('Vary','Origin');res.setHeader('Access-Control-Allow-Credentials','true');res.setHeader('Access-Control-Allow-Headers','Content-Type, X-NG-Request');res.setHeader('Access-Control-Allow-Methods','GET,POST,PUT,OPTIONS');}}
function json(res,status,body,headers={}){res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store',...headers});res.end(JSON.stringify(body));}
async function body(req,max=9*1024*1024){let size=0,chunks=[];for await(const c of req){size+=c.length;if(size>max)throw publicError('Request is too large.',413,'PAYLOAD_TOO_LARGE');chunks.push(c);}if(!chunks.length)return {};try{return JSON.parse(Buffer.concat(chunks).toString('utf8'));}catch{throw publicError('Request body must be valid JSON.');}}
function requireCsrfHeader(req){if(['POST','PUT','PATCH','DELETE'].includes(req.method)&&req.headers['x-ng-request']!=='web')throw publicError('Missing request verification header.',403,'CSRF_CHECK_FAILED');}
function rateLimit(req,bucket='general',max=120,windowMs=60_000){const ip=req.socket.remoteAddress||'local',key=`${bucket}:${ip}`,now=Date.now(),r=limits.get(key);if(!r||now-r.start>windowMs){limits.set(key,{start:now,count:1});return;}r.count++;if(r.count>max)throw publicError('Too many requests. Try again shortly.',429,'RATE_LIMITED');}
function cents(n){const v=Number(n);if(!Number.isFinite(v))throw publicError('Invalid amount.');return Math.round(v*100);}
function dollars(c){return Math.round(Number(c||0))/100;}
function tx(db,fn){db.exec('BEGIN IMMEDIATE');try{const r=fn();db.exec('COMMIT');return r;}catch(e){try{db.exec('ROLLBACK');}catch{}throw e;}}
function makeSession(db,userId,level,res){const token=sessionToken(),hash=sha256(token),now=Date.now();db.prepare('INSERT INTO sessions (token_hash,user_id,auth_level,expires_at,created_at) VALUES (?,?,?,?,?)').run(hash,userId,level,now+SESSION_MS,now);res.setHeader('Set-Cookie',sessionCookie(token));return token;}
function auth(db,req,level='full'){const token=parseCookies(req.headers.cookie).ng_session;if(!token)throw publicError('Sign in required.',401,'AUTH_REQUIRED');const hash=sha256(token),row=db.prepare('SELECT s.*,u.verified_at,u.mfa_enabled FROM sessions s JOIN users u ON u.id=s.user_id WHERE token_hash=?').get(hash);if(!row||row.expires_at<Date.now()){if(row)db.prepare('DELETE FROM sessions WHERE token_hash=?').run(hash);throw publicError('Session expired. Sign in again.',401,'AUTH_REQUIRED');}if(!row.verified_at)throw publicError('Contact verification required.',403,'VERIFY_REQUIRED');if(level==='full'&&(row.auth_level!=='full'||!row.mfa_enabled))throw publicError('Two-factor authentication required.',401,'MFA_REQUIRED');return {...row,tokenHash:hash};}
async function issueVerification(db,user){const identifier=decrypt(user.identifier_ciphertext),code=randomCode(),now=Date.now();db.prepare('DELETE FROM verification_codes WHERE user_id=?').run(user.id);db.prepare('INSERT INTO verification_codes (id,user_id,code_hash,expires_at,attempts,created_at) VALUES (?,?,?,?,?,?)').run(randomId(),user.id,codeHash(user.id,code),now+VERIFY_MS,0,now);const sent=await sendVerification({channel:user.channel,identifier,code});return sent.devCode;}
function requireProfile(db,userId){if(!profileFor(db,userId))throw publicError('Complete your profile before using marketplace actions.',403,'PROFILE_REQUIRED');}
function rentalView(db,id,userId){const r=db.prepare(`SELECT r.*,t.owner_id,t.title tool_title FROM rentals r JOIN tools t ON t.id=r.tool_id WHERE r.id=?`).get(id);if(!r)return null;if(r.renter_id!==userId&&r.owner_id!==userId)return null;return {id:r.id,toolId:r.tool_id,toolTitle:r.tool_title,days:r.days,rental:dollars(r.rental_cents),deposit:dollars(r.deposit_cents),fee:dollars(r.fee_cents),credits:dollars(r.credits_used_cents),due:dollars(r.amount_due_cents),status:r.status,role:r.renter_id===userId?'renter':'owner'};}

export function createNeighborhoodGarageServer({db=openDb()}={}){
 return createServer(async(req,res)=>{
  cors(req,res);if(req.method==='OPTIONS'){res.writeHead(204);res.end();return;}
  try{
   rateLimit(req);requireCsrfHeader(req);
   const url=new URL(req.url,'http://localhost');const path=url.pathname;
   if(req.method==='GET'&&path==='/health'){return json(res,200,{ok:true,service:'neighborhood-garage-api'});}
   if(req.method==='POST'&&path==='/auth/signup'){
    rateLimit(req,'auth',20);const b=await body(req,64*1024),channel=String(b.channel||''),identifier=normalizeIdentifier(channel,b.identifier),hash=identifierHash(channel,identifier);if(db.prepare('SELECT 1 FROM users WHERE identifier_hash=?').get(hash))throw publicError('An account already exists for that email or phone.',409,'ACCOUNT_EXISTS');const pass=passwordRecord(b.password),id=randomId(),now=Date.now();db.prepare('INSERT INTO users (id,channel,identifier_hash,identifier_ciphertext,password_salt,password_hash,verified_at,mfa_secret_ciphertext,mfa_enabled,created_at) VALUES (?,?,?,?,?,?,?,?,?,?)').run(id,channel,hash,encrypt(identifier),pass.salt,pass.hash,null,null,0,now);const devCode=await issueVerification(db,db.prepare('SELECT * FROM users WHERE id=?').get(id));return json(res,201,{accountId:id,verificationRequired:true,...(devCode?{devCode}:{})});
   }
   if(req.method==='POST'&&path==='/auth/resend'){
    rateLimit(req,'auth',15);const b=await body(req,32*1024),u=db.prepare('SELECT * FROM users WHERE id=?').get(String(b.accountId||''));if(!u)throw publicError('Account not found.',404,'NOT_FOUND');if(u.verified_at)throw publicError('Account is already verified.',409,'ALREADY_VERIFIED');const devCode=await issueVerification(db,u);return json(res,200,{sent:true,...(devCode?{devCode}:{})});
   }
   if(req.method==='POST'&&path==='/auth/verify'){
    rateLimit(req,'auth',25);const b=await body(req,32*1024),userId=String(b.accountId||''),row=db.prepare('SELECT * FROM verification_codes WHERE user_id=? ORDER BY created_at DESC LIMIT 1').get(userId);if(!row||row.expires_at<Date.now())throw publicError('Verification code expired. Request a new code.',400,'CODE_EXPIRED');if(row.attempts>=5)throw publicError('Too many incorrect codes. Request a new code.',429,'CODE_LOCKED');if(codeHash(userId,String(b.code||''))!==row.code_hash){db.prepare('UPDATE verification_codes SET attempts=attempts+1 WHERE id=?').run(row.id);throw publicError('Incorrect verification code.',400,'INVALID_CODE');}const now=Date.now();db.prepare('UPDATE users SET verified_at=? WHERE id=?').run(now,userId);db.prepare('DELETE FROM verification_codes WHERE user_id=?').run(userId);makeSession(db,userId,'verified',res);return json(res,200,{verified:true,mfaSetupRequired:true});
   }
   if(req.method==='POST'&&path==='/auth/2fa/setup'){
    const s=auth(db,req,'verified');const u=db.prepare('SELECT * FROM users WHERE id=?').get(s.user_id);if(u.mfa_enabled)throw publicError('Two-factor authentication is already enabled.',409,'MFA_ALREADY_ENABLED');const secret=newTotpSecret(),identifier=decrypt(u.identifier_ciphertext);db.prepare('UPDATE users SET mfa_secret_ciphertext=? WHERE id=?').run(encrypt(secret),u.id);return json(res,200,{secret,otpauthUri:otpauthUri(secret,`Neighborhood Garage:${identifier}`)});
   }
   if(req.method==='POST'&&path==='/auth/2fa/enable'){
    const s=auth(db,req,'verified'),b=await body(req,32*1024),u=db.prepare('SELECT * FROM users WHERE id=?').get(s.user_id);if(!u.mfa_secret_ciphertext)throw publicError('Start two-factor setup first.',409,'MFA_SETUP_REQUIRED');const secret=decrypt(u.mfa_secret_ciphertext);if(!verifyTotp(secret,b.code))throw publicError('Incorrect authenticator code.',400,'INVALID_MFA_CODE');db.prepare('UPDATE users SET mfa_enabled=1 WHERE id=?').run(u.id);db.prepare('UPDATE sessions SET auth_level=? WHERE token_hash=?').run('full',s.tokenHash);return json(res,200,{enabled:true,profileRequired:!profileFor(db,u.id)});
   }
   if(req.method==='POST'&&path==='/auth/login'){
    rateLimit(req,'auth',20);const b=await body(req,64*1024),raw=String(b.identifier||'').trim();let u=null;for(const channel of ['email','phone']){try{u=db.prepare('SELECT * FROM users WHERE identifier_hash=?').get(identifierHash(channel,raw));if(u)break;}catch{}}if(!u||!verifyPassword(String(b.password||''),u.password_salt,u.password_hash))throw publicError('Incorrect email/phone or password.',401,'BAD_CREDENTIALS');if(!u.verified_at)throw publicError('Verify your email or phone before signing in.',403,'VERIFY_REQUIRED');if(!u.mfa_enabled)throw publicError('Two-factor setup must be completed.',403,'MFA_SETUP_REQUIRED');const id=randomId(),now=Date.now();db.prepare('INSERT INTO login_challenges (id,user_id,expires_at,used_at,created_at) VALUES (?,?,?,?,?)').run(id,u.id,now+CHALLENGE_MS,null,now);return json(res,200,{mfaRequired:true,challengeId:id});
   }
   if(req.method==='POST'&&path==='/auth/login/2fa'){
    rateLimit(req,'auth',30);const b=await body(req,32*1024),c=db.prepare('SELECT * FROM login_challenges WHERE id=?').get(String(b.challengeId||''));if(!c||c.used_at||c.expires_at<Date.now())throw publicError('Two-factor challenge expired. Sign in again.',400,'CHALLENGE_EXPIRED');const u=db.prepare('SELECT * FROM users WHERE id=?').get(c.user_id),secret=decrypt(u.mfa_secret_ciphertext);if(!verifyTotp(secret,b.code))throw publicError('Incorrect authenticator code.',401,'INVALID_MFA_CODE');db.prepare('UPDATE login_challenges SET used_at=? WHERE id=?').run(Date.now(),c.id);makeSession(db,u.id,'full',res);return json(res,200,{signedIn:true});
   }
   if(req.method==='POST'&&path==='/auth/logout'){
    const token=parseCookies(req.headers.cookie).ng_session;if(token)db.prepare('DELETE FROM sessions WHERE token_hash=?').run(sha256(token));res.setHeader('Set-Cookie',sessionCookie('',{clear:true}));return json(res,200,{signedOut:true});
   }
   if(req.method==='GET'&&path==='/profile'){const s=auth(db,req);return json(res,200,{profile:profileFor(db,s.user_id),complete:!!profileFor(db,s.user_id)});}
   if(req.method==='PUT'&&path==='/profile'){
    const s=auth(db,req),p=saveProfile(db,s.user_id,await body(req,64*1024));const starter=Number(process.env.NG_STARTING_CREDITS_CENTS||0);if(starter>0&&!db.prepare(`SELECT 1 FROM credit_ledger WHERE user_id=? AND reason='starter_credit'`).get(s.user_id))db.prepare('INSERT INTO credit_ledger (id,user_id,rental_id,amount_cents,reason,idempotency_key,created_at) VALUES (?,?,?,?,?,?,?)').run(randomId(),s.user_id,null,starter,'starter_credit',`starter:${s.user_id}`,Date.now());return json(res,200,{profile:p});
   }
   if(req.method==='GET'&&path==='/state'){const s=auth(db,req);return json(res,200,stateFor(db,s.user_id));}
   if(req.method==='POST'&&path==='/tools'){
    const s=auth(db,req);requireProfile(db,s.user_id);const b=await body(req);const title=String(b.title||'').trim(),category=String(b.category||'').trim(),description=String(b.description||'').trim(),condition=String(b.condition||'').trim(),rate=cents(b.rate),deposit=cents(b.deposit);if(!title||title.length>100||!['Power tools','Outdoor','Home & DIY','Garden'].includes(category)||!description||description.length>2000||!condition||condition.length>1000||rate<100||rate>100000||deposit<0||deposit>1_000_000)throw publicError('Invalid tool listing fields.');if(b.photo&&!/^data:image\/(jpeg|png|webp);base64,/.test(b.photo))throw publicError('Invalid tool photo.');const id='NG'+Date.now().toString(36).toUpperCase()+Math.floor(Math.random()*1000),now=Date.now();db.prepare('INSERT INTO tools (id,owner_id,title,category,description,condition,rate_cents,deposit_cents,approximate_lat,approximate_lng,photo_data,available,created_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)').run(id,s.user_id,title,category,description,condition,rate,deposit,41.883,-87.633,b.photo||null,1,now);return json(res,201,{id,title,category,description,condition,rate:dollars(rate),deposit:dollars(deposit),owner:'You',rating:5,lat:41.883,lng:-87.633,photo:b.photo||undefined});
   }
   if(req.method==='POST'&&path==='/scans'){
    const s=auth(db,req);requireProfile(db,s.user_id);const b=await body(req);const result=await analyzeToolPhoto(b.photo,{stage:b.stage||'baseline'});return json(res,200,result);
   }
   if(req.method==='POST'&&path==='/rentals'){
    const s=auth(db,req);requireProfile(db,s.user_id);const b=await body(req,64*1024),toolId=String(b.toolId||''),days=Number(b.days),idem=String(b.idempotencyKey||'');if(!Number.isInteger(days)||days<1||days>30||!idem)throw publicError('Invalid rental request.');const existing=db.prepare('SELECT id FROM rentals WHERE idempotency_key=? AND renter_id=?').get(idem,s.user_id);if(existing)return json(res,200,{...rentalView(db,existing.id,s.user_id),idempotent:true});const t=db.prepare('SELECT * FROM tools WHERE id=?').get(toolId);if(!t||t.owner_id===s.user_id||!t.available)throw publicError('Tool is unavailable.',409,'TOOL_UNAVAILABLE');if(db.prepare(`SELECT 1 FROM rentals WHERE tool_id=? AND status IN ('reserved','out','review','disputed')`).get(toolId))throw publicError('Tool is already reserved.',409,'TOOL_UNAVAILABLE');const rentalCents=t.rate_cents*days,feeCents=Math.round(rentalCents*.05),available=creditsCents(db,s.user_id),total=rentalCents+t.deposit_cents,credits=Math.min(available,total),due=total-credits,id=randomId(),now=Date.now();tx(db,()=>{db.prepare('INSERT INTO rentals (id,tool_id,renter_id,status,days,rental_cents,deposit_cents,fee_cents,credits_used_cents,amount_due_cents,payment_reference,idempotency_key,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?)').run(id,toolId,s.user_id,'reserved',days,rentalCents,t.deposit_cents,feeCents,credits,due,'pending',idem,now,now);if(credits>0)db.prepare('INSERT INTO credit_ledger (id,user_id,rental_id,amount_cents,reason,idempotency_key,created_at) VALUES (?,?,?,?,?,?,?)').run(randomId(),s.user_id,id,-credits,'rental_checkout',`checkout:${id}`,now);});let payment;try{payment=await authorizePayment({amountCents:due,rentalId:id,userId:s.user_id});}catch(e){tx(db,()=>{db.prepare(`DELETE FROM credit_ledger WHERE rental_id=? AND reason='rental_checkout'`).run(id);db.prepare('DELETE FROM rentals WHERE id=?').run(id);});throw publicError(e.message,502,'PAYMENT_FAILED');}db.prepare('UPDATE rentals SET payment_reference=? WHERE id=?').run(payment.reference,id);return json(res,201,{...rentalView(db,id,s.user_id),payment:payment.simulated?'simulated':'provider'});
   }
   const m=path.match(/^\/rentals\/([^/]+)\/(pickup|return|approve|dispute|reviews)$/);
   if(req.method==='POST'&&m){
    const s=auth(db,req);requireProfile(db,s.user_id);const [_,id,action]=m,b=await body(req);const r=db.prepare(`SELECT r.*,t.owner_id,t.title tool_title FROM rentals r JOIN tools t ON t.id=r.tool_id WHERE r.id=?`).get(id);if(!r)throw publicError('Rental not found.',404,'NOT_FOUND');
    if(action==='pickup'){if(r.renter_id!==s.user_id||r.status!=='reserved')throw publicError('Pickup is not available.',403,'NOT_ALLOWED');if(String(b.code||'').toUpperCase()!==r.tool_id)throw publicError('That tracking code does not match this tool.');db.prepare('UPDATE rentals SET status=?,updated_at=? WHERE id=?').run('out',Date.now(),id);return json(res,200,rentalView(db,id,s.user_id));}
    if(action==='return'){if(r.renter_id!==s.user_id||r.status!=='out')throw publicError('Return is not available.',403,'NOT_ALLOWED');if(!b.photo)throw publicError('A return photo is required.');if(b.method!=='dropoff'&&String(b.code||'').toUpperCase()!==r.tool_id)throw publicError('Tracking code does not match.');const assessment=await analyzeToolPhoto(b.photo,{stage:'return'});db.prepare('UPDATE rentals SET status=?,return_photo_ciphertext=?,assessment_json=?,handoff_method=?,updated_at=? WHERE id=?').run('review',encrypt(b.photo),JSON.stringify(assessment),String(b.method||'scan'),Date.now(),id);return json(res,200,rentalView(db,id,s.user_id));}
    if(action==='approve'){if(r.owner_id!==s.user_id||r.status!=='review')throw publicError('Approval is not available.',403,'NOT_ALLOWED');tx(db,()=>{db.prepare('UPDATE rentals SET status=?,updated_at=? WHERE id=?').run('complete',Date.now(),id);db.prepare('INSERT INTO credit_ledger (id,user_id,rental_id,amount_cents,reason,idempotency_key,created_at) VALUES (?,?,?,?,?,?,?)').run(randomId(),r.renter_id,id,r.deposit_cents,'deposit_refund',`deposit:${id}`,Date.now());});return json(res,200,rentalView(db,id,s.user_id));}
    if(action==='dispute'){if(r.owner_id!==s.user_id||r.status!=='review')throw publicError('Dispute is not available.',403,'NOT_ALLOWED');db.prepare('UPDATE rentals SET status=?,updated_at=? WHERE id=?').run('disputed',Date.now(),id);return json(res,200,rentalView(db,id,s.user_id));}
    if(action==='reviews'){if(r.renter_id!==s.user_id||r.status!=='complete')throw publicError('Review unavailable.',403,'NOT_ALLOWED');const rating=Number(b.rating),text=String(b.text||'').trim();if(!Number.isInteger(rating)||rating<1||rating>5||text.length>1000)throw publicError('Invalid review.');try{db.prepare('INSERT INTO reviews (id,rental_id,author_id,rating,body,created_at) VALUES (?,?,?,?,?,?)').run(randomId(),id,s.user_id,rating,text,Date.now());}catch{throw publicError('A review already exists for this rental.',409,'DUPLICATE_REVIEW');}return json(res,201,{saved:true});}
   }
   if(req.method==='POST'&&path==='/messages'){
    const s=auth(db,req);requireProfile(db,s.user_id);const b=await body(req,64*1024),text=String(b.text||'').trim();if(!text||text.length>2000)throw publicError('Enter a message up to 2,000 characters.');const recipient=publicProfileIdByName(db,b.peer);if(!recipient||recipient===s.user_id)throw publicError('Neighbor not found.',404,'NEIGHBOR_NOT_FOUND');const ownsPublicTool=db.prepare('SELECT 1 FROM tools WHERE owner_id=? LIMIT 1').get(recipient);const related=db.prepare(`SELECT 1 FROM rentals r JOIN tools t ON t.id=r.tool_id WHERE (r.renter_id=? AND t.owner_id=?) OR (r.renter_id=? AND t.owner_id=?) LIMIT 1`).get(s.user_id,recipient,recipient,s.user_id);if(!ownsPublicTool&&!related)throw publicError('Messaging is limited to marketplace neighbors.',403,'NOT_ALLOWED');db.prepare('INSERT INTO messages (id,sender_id,recipient_id,ciphertext,created_at) VALUES (?,?,?,?,?)').run(randomId(),s.user_id,recipient,encrypt(text),Date.now());return json(res,201,{sent:true});
   }
   return json(res,404,{error:'Not found.',code:'NOT_FOUND'});
  }catch(e){console.error(e.code||e.name,e.message);return json(res,e.status||500,{error:e.status?e.message:'Server error.',code:e.code||'SERVER_ERROR'});}
 });
}

if(import.meta.url===`file://${process.argv[1]}`){const server=createNeighborhoodGarageServer();server.listen(PORT,'127.0.0.1',()=>console.log(`Neighborhood Garage API listening on http://127.0.0.1:${PORT}`));}
