const {chromium}=require('playwright');
const assert=require('node:assert/strict');
const path=require('node:path'),os=require('node:os');
const desktop=path.join(os.tmpdir(),'ng-desktop.png'),mobile=path.join(os.tmpdir(),'ng-mobile.png');
(async()=>{const browser=await chromium.launch({headless:true});const page=await browser.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('http://localhost:5173');await page.getByRole('heading',{name:'Big plans. Neighborly prices.'}).waitFor();
for(const width of [320,375,768,1280]){await page.setViewportSize({width,height:900});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),`Overflow at ${width}`);}
await page.setViewportSize({width:1280,height:900});await page.screenshot({path:desktop,fullPage:true});
await page.getByRole('button',{name:/20V cordless drill kit/}).click();await page.getByRole('button',{name:'Reserve tool',exact:true}).click();await page.getByRole('button',{name:'Scan at pickup'}).click();await page.getByRole('button',{name:'Simulate barcode scan',exact:true}).click();await page.getByRole('button',{name:'Confirm pickup'}).click();await page.getByRole('button',{name:'Return tool',exact:true}).click();await page.getByRole('button',{name:'Simulate barcode scan',exact:true}).click();await page.locator('#return-photo').setInputFiles(desktop);await page.waitForTimeout(300);await page.getByRole('button',{name:'Submit scan for owner review'}).click();await page.getByRole('link',{name:'My garage',exact:true}).click();await page.getByRole('button',{name:/Approve & return/}).click();await page.getByRole('link',{name:'Profile & credits'}).click();await page.getByText('$112.00',{exact:true}).waitFor();
await page.getByRole('button',{name:'＋ Lend a tool',exact:true}).click();await page.locator('#photo').setInputFiles(desktop);await page.waitForTimeout(300);await page.getByRole('button',{name:/Simulate AI scan/}).click();
assert.equal(await page.locator('input[name="title"]').inputValue(),'20V cordless drill kit');await page.getByRole('checkbox').check();await page.getByRole('button',{name:'Publish tool',exact:true}).click();await page.getByRole('heading',{name:'Your tool shelf'}).waitFor();
await page.getByRole('link',{name:'Messages',exact:true}).click();await page.getByRole('textbox',{name:'Your message'}).fill('Tuesday at 10 works!');await page.getByRole('button',{name:'Send',exact:true}).click();await page.getByText('Tuesday at 10 works!',{exact:true}).waitFor();await page.reload();await page.getByText('Tuesday at 10 works!',{exact:true}).waitFor();
await page.getByRole('switch',{name:'Demo Mode'}).uncheck();await page.getByText(/Live mode needs a backend/).waitFor();await page.getByRole('switch',{name:'Demo Mode'}).check();await page.getByRole('link',{name:'Explore tools',exact:true}).click();await page.setViewportSize({width:375,height:812});await page.screenshot({path:mobile,fullPage:true});assert.deepEqual(errors,[]);console.log('PASS: responsive widths, reservation, pickup, return, approval, credits, listing autofill, chat persistence, live fail-closed');await browser.close();})().catch(e=>{console.error(e);process.exit(1)});
