import {test} from 'node:test';
import assert from 'node:assert/strict';
import {edgeHandler} from './helpers/edge-handler.mjs';
class HttpError extends Error{constructor(message,status=400){super(message);this.status=status;}}
const checked=r=>{if(r.error)throw r.error;return r.data;};
const endpoint=f=>async req=>{try{return Response.json(await f(req));}catch(error){return Response.json({error:error.message},{status:error.status||400});}};
const png=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII=','base64');
async function helpers(mode='sandbox'){const handler=await edgeHandler('supabase/functions/upload-photo/index.ts',{HttpError,checked,endpoint,env:k=>k==='STRIPE_MODE'?mode:undefined,authenticate:async()=>{throw Error('unused');}});return handler.creditHelpers;}
test('sandbox fee is itemized, grossed up and never applied to internal credits',async()=>{const {paymentQuote}=await helpers();assert.deepEqual(paymentQuote(0),{principalCents:0,processingFeeCents:0,totalCents:0,policy:'credits-no-fee'});for(const principal of [50,100,1250,6200,100000]){const q=paymentQuote(principal);assert.equal(q.totalCents,q.principalCents+q.processingFeeCents);assert(q.totalCents-Math.round(q.totalCents*.029)-30>=principal);}for(const invalid of [-1,1.1,NaN,Infinity])assert.throws(()=>paymentQuote(invalid),/Invalid payment/);});
test('live external quotes remain blocked while credit spending works',async()=>{const {paymentQuote}=await helpers('live');assert.equal(paymentQuote(0).totalCents,0);assert.throws(()=>paymentQuote(100),/approved payment-method/);});
test('server removes PNG location/text metadata and rejects trailing or oversized containers',async()=>{const {sanitizeImage}=await helpers();const metadata=Buffer.from('GPSLatitude=41.88;GPSLongitude=-87.63');const chunk=Buffer.alloc(metadata.length+12);chunk.writeUInt32BE(metadata.length);chunk.write('tEXt',4);metadata.copy(chunk,8);const withMetadata=Buffer.concat([png.subarray(0,33),chunk,png.subarray(33)]);const cleaned=sanitizeImage(withMetadata);assert.equal(cleaned.type,'image/png');assert.deepEqual(Buffer.from(cleaned.bytes),png);assert.throws(()=>sanitizeImage(Buffer.concat([png,Buffer.from('payload')])),/valid JPEG or PNG/);const bomb=Buffer.from(png);bomb.writeUInt32BE(6000,16);bomb.writeUInt32BE(6000,20);assert.throws(()=>sanitizeImage(bomb),/valid JPEG or PNG/);assert.throws(()=>sanitizeImage(Buffer.alloc(8388609)),/valid JPEG or PNG/);});
test('return uploads require rental membership and cannot bypass the sanitized storage endpoint',async()=>{const user={id:'owner'},calls=[];const query={select(){return this;},eq(){return this;},single:async()=>({data:{owner_id:'other',renter_id:'renter'}})};const handler=await edgeHandler('supabase/functions/upload-photo/index.ts',{HttpError,checked,endpoint,authenticate:async()=>({user,admin:{from:()=>query,rpc:async()=>{calls.push('quota');return {data:true};},storage:{from:()=>({upload:async()=>{calls.push('upload');return {data:{}};}})}}})});const body=new FormData();body.set('photo',new File([png],'photo.png',{type:'image/png'}));body.set('kind','return');body.set('rentalId','fixture');const response=await handler(new Request('https://fixture/functions/v1/upload-photo',{method:'POST',body}));assert.equal(response.status,404);assert.deepEqual(calls,[]);});
test('operator evidence and money actions require both MFA and administrator allowlisting',async()=>{for(const [aal,allowed,hasVerifiedMfa]of [['aal1',true,true],['aal2',false,true],['aal2',true,false]]){let rpcCalls=0;const handler=await edgeHandler('supabase/functions/support/index.ts',{HttpError,checked,endpoint,authenticate:async()=>({user:{id:'fixture'},claims:{aal},hasVerifiedMfa,admin:{rpc:async()=>{rpcCalls++;return {data:allowed};},from:()=>{throw Error('Evidence accessed without authorization');}}})});for(const action of ['details','operate']){const response=await handler(new Request('https://fixture/functions/v1/support',{method:'POST',body:JSON.stringify({action})}));assert.equal(response.status,403);}assert.equal(rpcCalls,2);}});
