import {test} from 'node:test';
import assert from 'node:assert/strict';
import {database} from './helpers/local-database.mjs';
import {readFile} from 'node:fs/promises';
test('installed Stripe helpers keep working with a fixed catalog search path',async t=>{
 const db=await database();t.after(()=>db.close());
 await db.exec(`create schema stripe;create table stripe._rate_limits(key text primary key,count integer,window_start timestamptz);
 create function stripe.check_rate_limit(rate_key text,max_requests integer,window_seconds integer) returns void language plpgsql as $$begin
 insert into stripe._rate_limits values(rate_key,1,clock_timestamp()) on conflict(key) do update set count=_rate_limits.count+1;
 if (select count from stripe._rate_limits where key=rate_key)>max_requests then raise exception 'Rate limit exceeded';end if;end$$;
 create table stripe.fixture(updated_at timestamptz,_updated_at timestamptz);
 create function stripe.set_updated_at() returns trigger language plpgsql as $$begin new=jsonb_populate_record(new,jsonb_build_object('updated_at',now(),'_updated_at',now()));return new;end$$;
 create function stripe.set_updated_at_metadata() returns trigger language plpgsql as $$begin new.updated_at=now();return new;end$$;
 create trigger first before insert on stripe.fixture for each row execute function stripe.set_updated_at();
 create trigger second before insert on stripe.fixture for each row execute function stripe.set_updated_at_metadata();`);
 await db.exec(await readFile('supabase/migrations/20261005002000_stripe_sync_search_paths.sql','utf8'));
 const settings=(await db.query("select proconfig from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='stripe'")).rows;
 assert.equal(settings.length,3);assert(settings.every(p=>p.proconfig.includes('search_path=pg_catalog')));
 await db.query("select stripe.check_rate_limit('fixture',1,60)");await assert.rejects(()=>db.query("select stripe.check_rate_limit('fixture',1,60)"),/Rate limit exceeded/);
 await db.exec('insert into stripe.fixture default values');const row=(await db.query('select * from stripe.fixture')).rows[0];assert(row.updated_at);assert(row._updated_at);
});
test('operator grants are verified, audited and unavailable to ordinary accounts',async t=>{
 const db=await database();t.after(()=>db.close());const operator=crypto.randomUUID(),unverified=crypto.randomUUID(),request=crypto.randomUUID();
 await db.query('insert into auth.users(id,email,email_confirmed_at) values($1,$2,now()),($3,$4,null)',[operator,'operator@fixture.invalid',unverified,'unverified@fixture.invalid']);
 const grant=(id,enabled=true,req=request)=>db.query('select set_operator_access($1,$2,$3,$4,$5)',[id,enabled,'Confirmed sandbox operator identity.',req,'Authenticated repository owner']);
 await assert.rejects(()=>grant(unverified),/verified email/);await grant(operator);await grant(operator);
 assert.equal((await db.query('select count(*) n from private.operation_audit')).rows[0].n,1);
 assert.equal((await db.query('select operator_allowed($1) allowed',[operator])).rows[0].allowed,true);
 await assert.rejects(()=>grant(operator,false),/mismatch/);
 await grant(operator,false,crypto.randomUUID());assert.equal((await db.query('select operator_allowed($1) allowed',[operator])).rows[0].allowed,false);
 await db.query("insert into private.account_restrictions(user_id,reason) values($1,'Sandbox moderation fixture')",[operator]);
 await db.query('insert into private.operator_accounts(user_id) values($1)',[operator]);assert.equal((await db.query('select operator_allowed($1) allowed',[operator])).rows[0].allowed,false);
 await db.query("select check_request_access($1,'support',60)",[operator]);await assert.rejects(()=>db.query("select check_request_access($1,'rental-action',60)",[operator]),/Account unavailable/);
 await db.exec('set role authenticated');await db.query("select set_config('request.jwt.claim.sub',$1,false),set_config('request.jwt.claims',$2,false)",[operator,JSON.stringify({aal:'aal1'})]);
 await assert.rejects(()=>db.query("insert into tools(owner_id,title,category,rate_cents,deposit_cents) values($1,'Restricted listing','Power tools',100,100)",[operator]),/row-level security/);await db.exec('reset role');
 await db.exec('set role authenticated');await assert.rejects(()=>grant(operator,true,crypto.randomUUID()),/permission denied/);await db.exec('reset role');
});
test('notification leases prevent overlap and stale completion; sandbox capture is idempotent',async t=>{
 const db=await database();t.after(()=>db.close());const user=crypto.randomUUID(),other=crypto.randomUUID();await db.query('insert into auth.users(id) values($1),($2)',[user,other]);
 await db.query("insert into notifications(user_id,message) values($1,'First update'),($2,'Private other update')",[user,other]);
 const jobs=(await db.query('select * from claim_notifications()')).rows;assert.equal(jobs.length,2);assert.equal((await db.query('select * from claim_notifications()')).rows.length,0);
 const job=jobs[0];await db.query("update private.notification_delivery set lease_expires_at=now()-interval '1 second',next_attempt_at=now()-interval '1 second' where notification_id=$1",[job.id]);
 const retry=(await db.query('select * from claim_notifications()')).rows[0];assert.notEqual(retry.lease_token,job.lease_token);
 assert.equal((await db.query("select finish_notification($1,$2,true,'email') done",[job.id,job.lease_token])).rows[0].done,false);
 assert.equal((await db.query('select capture_notification($1,$2) done',[retry.id,retry.lease_token])).rows[0].done,true);
 assert.equal((await db.query('select capture_notification($1,$2) done',[retry.id,retry.lease_token])).rows[0].done,false);
 const captured=(await db.query('select * from private.notification_previews')).rows;assert.equal(captured.length,1);assert(!JSON.stringify(captured).includes('Private other update'));assert(!JSON.stringify(captured).includes('First update'));assert.match(captured[0].body,/smkimbal.github.io/);
 const pending=jobs[1];await db.query('select finish_notification($1,$2,false,null,$3)',[pending.id,pending.lease_token,'Delivery failed']);const failed=(await db.query('select * from private.notification_delivery where notification_id=$1',[pending.id])).rows[0];assert.equal(failed.lease_token,null);assert(failed.next_attempt_at>new Date());
 await db.query('update private.notification_delivery set attempts=12,next_attempt_at=now() where notification_id=$1',[pending.id]);assert.equal((await db.query('select * from claim_notifications()')).rows.length,0);
 const status=(await db.query('select notification_delivery_status() status')).rows[0].status;assert.equal(status.failed,1);assert.equal(status.captured,1);assert.equal(status.emailed,0);
 await assert.rejects(()=>db.query('select retry_notification($1,$2,$3,gen_random_uuid())',[user,pending.id,'Investigated the delivery service.']),/Operator access/);
 await db.query('insert into private.operator_accounts(user_id) values($1)',[user]);const request=crypto.randomUUID();
 await db.query('select retry_notification($1,$2,$3,$4)',[user,pending.id,'Investigated the delivery service.',request]);await db.query('select retry_notification($1,$2,$3,$4)',[user,pending.id,'Investigated the delivery service.',request]);assert.equal((await db.query("select count(*) n from private.operation_audit where action='retry-notification'")).rows[0].n,1);
 const retried=(await db.query('select * from claim_notifications()')).rows[0];assert.equal(retried.id,pending.id);assert.notEqual(retried.lease_token,pending.lease_token);
 await db.exec('set role authenticated');await db.query("select set_config('request.jwt.claim.sub',$1,false),set_config('request.jwt.claims',$2,false)",[user,JSON.stringify({aal:'aal1'})]);
 assert.equal((await db.query('select notification_summary() summary')).rows[0].summary.unread,1);
 assert.equal((await db.query("update notifications set read_at=now() where user_id=$1 returning id",[other])).rows.length,0);
 assert.equal((await db.query('select * from notifications')).rows.length,1);
 await assert.rejects(()=>db.query('select notification_delivery_status()'),/permission denied/);await assert.rejects(()=>db.query('select * from private.notification_previews'),/permission denied/);await assert.rejects(()=>db.query('select * from claim_notifications()'),/permission denied/);
 await db.exec('reset role');
});
