// Explicit opt-in integration test. Credentials are provisioned separately and never committed.
import {readFile,writeFile,mkdir} from 'node:fs/promises';
import {createServer} from 'node:http';
import {extname,resolve} from 'node:path';
import {createRequire} from 'node:module';
import assert from 'node:assert/strict';
import {X509Certificate,createHash} from 'node:crypto';
import {chromium} from 'playwright';
import {createClient} from '@supabase/supabase-js';
const users=JSON.parse(await readFile(process.env.QA_USERS||'.qa/users.json','utf8'));
const artifacts=process.env.QA_ARTIFACTS||'.qa';await mkdir(artifacts,{recursive:true});
const server=createServer(async(req,res)=>{try{const path=resolve('dist','.'+new URL(req.url,'http://localhost').pathname);if(!path.startsWith(resolve('dist')+'/'))throw Error();const body=await readFile(path.endsWith('/')?path+'index.html':path);res.setHeader('content-type',({'.js':'application/javascript','.css':'text/css','.svg':'image/svg+xml','.png':'image/png','.html':'text/html'})[extname(path)]||'text/html');res.end(body);}catch{try{res.setHeader('content-type','text/html');res.end(await readFile('dist/index.html'));}catch{res.writeHead(404).end();}}});
await new Promise(r=>server.listen(5173,'127.0.0.1',r));
const launch={headless:true};
if(process.env.CHROMIUM_PATH){launch.executablePath=process.env.CHROMIUM_PATH;const require=createRequire(process.env.CHROMIUM_HELPER);const imported=require('@sparticuz/chromium');const binary=imported.default||imported;launch.args=binary.args.filter(a=>a!=='--disable-web-security'&&a!=='--single-process');}
// Network proxy is optional; no disabled CORS or TLS checks.
if(process.env.QA_BROWSER_PROXY){const p=new URL(process.env.QA_BROWSER_PROXY);launch.proxy={server:p.origin,bypass:'127.0.0.1,localhost',...(p.username?{username:decodeURIComponent(p.username),password:decodeURIComponent(p.password)}:{})};}
if(process.env.QA_BROWSER_PROXY&&process.env.CODEX_PROXY_CERT){const cert=new X509Certificate(await readFile(process.env.CODEX_PROXY_CERT));const pin=createHash('sha256').update(cert.publicKey.export({type:'spki',format:'der'})).digest('base64');launch.args=[...(launch.args||[]),'--ignore-certificate-errors-spki-list='+pin];}
const browser=await chromium.launch(launch);const errors=[],checks=[];
const note=s=>{checks.push(s);console.log('PASS '+s);};
const cfg={url:'https://ilfpugydxlzmmxjfrmrv.supabase.co',key:'sb_publishable_fJpL5SCxPiuXgbaxlznTCg_TaScENEx'};
const pageFor=async u=>{const c=await browser.newContext({viewport:{width:375,height:812},geolocation:{latitude:41.88,longitude:-87.63},permissions:['geolocation']});const p=await c.newPage();p.on('pageerror',e=>errors.push(e.message));p.on('requestfailed',r=>console.log('NETWORK',new URL(r.url()).origin,r.failure()?.errorText));p.setDefaultTimeout(20000);await p.goto('http://127.0.0.1:5173/');await p.locator('#signin [name=email]').fill(u.email);await p.locator('#signin [name=password]').fill(u.password);await p.locator('#signin button.primary').click();await p.waitForSelector('#profile-form, .topbar', {timeout:30000});if(await p.locator('#profile-form').count()){for(const [name,value] of Object.entries({display_name:'QA '+u.role,neighborhood:'QA Oak Grove',city:'Chicago',state:'IL',bio:'Temporary integration-test profile.'}))await p.locator(`#profile-form [name=${name}]`).fill(value);await p.getByRole('button',{name:'Finish setup',exact:true}).click();}await p.locator('.topbar').waitFor();return p;};
const noOverflow=async p=>assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true,'page overflows mobile viewport');
try{
 const tool=JSON.parse(await readFile(artifacts+'/tool.json','utf8'));
 const owner=await pageFor(users[0]);await owner.getByRole('link',{name:'My garage',exact:true}).click();
 const renter=await pageFor(users[1]);await renter.getByRole('button',{name:'Profile',exact:true}).click();const initialBalance=Number((await renter.locator('.stats strong').first().textContent()).replace(/[^0-9.]/g,''));await renter.getByRole('link',{name:'Rentals',exact:true}).click();await renter.getByRole('button',{name:'Confirm pickup',exact:true}).click();
 await renter.locator('#pickup-form [name=code]').fill('WRONG');await renter.locator('#pickup-form button.primary').click();await renter.locator('#toast').filter({hasText:'Tracking code does not match'}).waitFor();assert(await renter.locator('dialog').isVisible());
 await renter.locator('#pickup-form [name=code]').fill(tool.tracking_code);await renter.locator('#pickup-form button.primary').click();await renter.getByRole('button',{name:'Return tool',exact:true}).waitFor();note('Invalid pickup code stays recoverable; matching code checks out the tool');
 await renter.getByRole('button',{name:'Return tool',exact:true}).click();await renter.locator('#return-form [name=photo]').setInputFiles({name:'return.png',mimeType:'image/png',buffer:Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII=','base64')});
 await renter.locator('#return-form [name=note]').fill('Returned clean with normal cosmetic wear.');await renter.locator('#return-form [name=handoff]').selectOption('dropoff');await renter.getByRole('button',{name:'Submit return',exact:true}).click();await renter.getByText('Awaiting owner review',{exact:true}).waitFor();note('Renter uploads private return evidence and selects agreed location drop-off');
 await owner.locator('.return-card').waitFor();note('Owner receives a live return-review prompt without reloading');assert(await owner.getByAltText('Original tool condition').isVisible());assert(await owner.getByAltText('Return condition').isVisible());await owner.evaluate(()=>scrollTo({top:0,behavior:'instant'}));await owner.screenshot({path:artifacts+'/owner-return-review.png',fullPage:true});
 await owner.getByRole('button',{name:/Approve \+ return/}).click();await owner.getByRole('heading',{name:'Pending payouts',exact:true}).waitFor();note('Owner sees both photographs; approval returns credits even while Stripe payout is unavailable');
 await renter.getByRole('button',{name:'Leave review',exact:true}).first().waitFor();await renter.getByRole('button',{name:'Leave review',exact:true}).click();await renter.locator('#review-form [name=body]').fill('Great tool, friendly neighbor. QA review.');await renter.getByRole('button',{name:'Publish review',exact:true}).click();await renter.locator('dialog').waitFor({state:'hidden'});await renter.getByRole('button',{name:'Profile',exact:true}).click();assert((await renter.locator('.stats').innerText()).includes(new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(initialBalance+75)));await renter.locator('.earned-badge.earned').filter({hasText:'Good neighbor'}).waitFor();note('Deposit balance increases by $75; renter earns Good neighbor and publishes a verified review');
 await owner.reload();await owner.getByRole('button',{name:'Profile',exact:true}).click();await owner.locator('.review-card').filter({hasText:'Great tool'}).last().waitFor();await noOverflow(owner);await owner.evaluate(()=>scrollTo({top:0,behavior:'instant'}));await owner.screenshot({path:artifacts+'/profile-badges-mobile.png',fullPage:true});note('Owner profile displays the real completed-rental review and badge progress');
 assert.deepEqual(errors,[]);await writeFile(artifacts+'/rental-results.json',JSON.stringify({checks,errors,payment:'Database fixture; no Stripe charge made'},null,2));
}catch(e){console.error('Rental simulation failed:',e.message);for(const [i,c]of browser.contexts().entries())for(const p of c.pages()){console.log('LAST TOAST',await p.locator('#toast').textContent());await p.screenshot({path:artifacts+`/rental-failure-${i}.png`,fullPage:true});}throw e;}
finally{await browser.close();server.close();}
