import {createServer} from 'node:http';
import {readFile} from 'node:fs/promises';
import {resolve,extname} from 'node:path';
import {chromium} from 'playwright';
import assert from 'node:assert/strict';
import {browserBackend,png} from './helpers/browser-backend.mjs';
import {localInput} from '../src/rental-workflow.js';
const backend=await browserBackend(),errors=[],output=process.env.NG_TEST_DIST||'dist-production';
const server=createServer(async(req,res)=>{try{
 const p=new URL(req.url,'http://localhost').pathname;
 if(p.startsWith('/__stripe/')){const s=backend.sessions.get(p.split('/').at(-1));if(req.method==='POST'){s.status='complete';s.payment_status='paid';const u=new URL(s.success_url);res.writeHead(303,{location:'http://127.0.0.1:5174/'+u.hash}).end();return;}res.setHeader('content-type','text/html');res.end('<form method="POST"><p>Sandbox transport fixture</p><button>Pay sandbox card</button></form>');return;}
 const path=resolve(output,'.'+(p==='/'?'/index.html':p)),data=await readFile(path);res.setHeader('content-type',({'.js':'application/javascript','.css':'text/css','.svg':'image/svg+xml','.html':'text/html','.png':'image/png'})[extname(path)]||'application/octet-stream');res.end(data);
 }catch(error){res.writeHead(404).end();}});
await new Promise(r=>server.listen(5174,'127.0.0.1',r));
const browser=await chromium.launch({headless:true,...(process.env.CHROMIUM_PATH?{executablePath:process.env.CHROMIUM_PATH,args:['--disable-gpu']}:{})});
let ownerPage,renterPage;
const origin='http://127.0.0.1:5174',photo={name:'tool.png',mimeType:'image/png',buffer:png};
async function page(){const ctx=await browser.newContext({viewport:{width:375,height:812},hasTouch:true,geolocation:{latitude:41.88,longitude:-87.63},permissions:['geolocation']});const p=await ctx.newPage();p.setDefaultTimeout(12000);p.on('pageerror',e=>errors.push(e.message));await p.routeWebSocket(/^wss:\/\/zbbespojxxoheavodtqs\.supabase\.co\//,s=>s.close());await p.route(/^https:\/\/zbbespojxxoheavodtqs\.supabase\.co\//,backend.intercept);return p;}
async function signup(p,email,name,path='/'){await p.goto(origin+'/#'+path);await p.locator('[data-auth-tab=signup]').click();for(const[k,v]of Object.entries({displayName:name,email,password:'qa-password-123!'}))await p.locator('#signup [name='+k+']').fill(v);await p.locator('#signup button.primary').click();await p.locator('#auth-notice').filter({hasText:'confirmation link'}).waitFor();await p.locator('#signin [name=password]').fill('qa-password-123!');await p.locator('#signin button.primary').click();await p.locator('#profile-form').waitFor();for(const[k,v]of Object.entries({neighborhood:'Oak Grove',city:'Chicago',state:'IL',bio:'I share tools with neighbors.'}))await p.locator('#profile-form [name='+k+']').fill(v);await p.getByRole('button',{name:'Finish setup',exact:true}).click();await p.locator('.topbar').waitFor();}
const booking=async id=>(await backend.sql('select * from public.rentals where id=$1',[id]))[0];
const balance=async id=>(await backend.sql('select coalesce(sum(amount_cents),0)::integer n from public.credit_ledger where user_id=$1',[id]))[0].n;
async function open(p,path){await p.goto(origin+'/#'+path);await p.reload();await p.locator('.topbar').waitFor();}
async function accept(p,id){await open(p,'/rental/'+id);await p.locator('[data-rental-action=accept]').click();await p.locator('#booking-locations [name=pickupLabel]').fill('Neighborhood locker');await p.locator('#booking-locations [name=pickupAddress]').fill('123 Main St, Chicago, front locker');await p.locator('#booking-locations [name=same]').uncheck();await p.locator('#booking-locations [name=returnType]').selectOption('owner_location');await p.locator('#booking-locations [name=returnLabel]').fill('Owner return spot');await p.locator('[data-gps=return]').click();await p.locator('[data-location=return] [data-gps-status]').filter({hasText:'Current location captured'}).waitFor();await p.locator('#booking-locations button.primary').click();await p.getByText('Approved · choose pickup and pay',{exact:true}).waitFor();}
async function plan(p,id,now=false){await open(p,'/rental/'+id);await p.locator('[data-rental-action=plan]').click();if(now)await p.locator('#pickup-plan [name=choice]').selectOption('now');await p.locator('#pickup-plan button.primary').click();}
async function request(p,tool,daysAhead=0){
 await open(p,'/tool/'+tool);
 if(daysAhead){await p.locator('#reservation-form [name=when]').selectOption('future');await p.locator('#reservation-form [name=pickupStart]').fill(localInput(Date.now()+daysAhead*86400000));await p.locator('#reservation-form [name=pickupStart]').dispatchEvent('change');}
 const windows=await p.locator('#reservation-form').evaluate(f=>Object.fromEntries(['pickupStart','pickupEnd','returnStart','returnEnd'].map(k=>[k,f.elements[k].value])));
 assert.equal(await p.locator('#days').textContent(),'1 day');
 const moved=localInput(new Date(windows.returnStart).getTime()+3*86400000);
 await p.locator('#reservation-form [name=returnStart]').fill(moved);await p.locator('#reservation-form [name=returnStart]').dispatchEvent('change');
 assert(new Date(await p.locator('#reservation-form [name=returnEnd]').inputValue())>=new Date(moved));
 await p.locator('#reservation-form [name=returnEnd]').fill(windows.pickupStart);await p.locator('#reservation-form [name=returnEnd]').dispatchEvent('change');
 assert(new Date(await p.locator('#reservation-form [name=returnEnd]').inputValue())>new Date(moved));
 await p.locator('#reservation-form').evaluate((f,w)=>{for(const[k,v]of Object.entries(w))f.elements[k].value=v;f.elements.returnEnd.dispatchEvent(new Event('change'));},windows);
 const end=localInput(new Date(windows.returnEnd).getTime()+2.5*3600000);
 await p.locator('#reservation-form [name=returnEnd]').fill(end);await p.locator('#reservation-form [name=returnEnd]').dispatchEvent('change');
 assert.equal(await p.locator('#days').textContent(),'1 day 2 hours 30 minutes');assert.match(await p.locator('#quote').textContent(),/\$11.04/);
 await p.locator('#reservation-form [name=returnEnd]').fill(windows.returnEnd);await p.locator('#reservation-form [name=returnEnd]').dispatchEvent('change');
 assert.equal(await p.locator('#reservation-form select[name=days]').count(),0);assert.match(await p.locator('#reservation-form').textContent(),/including time before collecting/);
 await p.locator('#reserve').click();await p.getByText('Awaiting owner approval',{exact:true}).waitFor();return p.url().split('/rental/')[1];
}
async function submitReturn(p,tool,stale=false){
 if(stale)await p.goto(origin+'/#/handoff/'+tool);else await open(p,'/handoff/'+tool);await p.locator('#return-form').waitFor();
 assert.equal(await p.locator('#return-form [name=code]').inputValue(),tool);
 assert.equal(await p.locator('#modal input[type=file]:visible').count(),1,'only the condition-photo picker is visible');
 if(!stale){
  // Exercise the actual video/canvas/JPEG path without a physical test camera.
  await p.evaluate(()=>{navigator.mediaDevices.getUserMedia=async()=>{const c=document.createElement('canvas');c.width=640;c.height=480;const ctx=c.getContext('2d');ctx.fillStyle='#4c7657';ctx.fillRect(0,0,640,480);const stream=c.captureStream(10);window.conditionTestTracks=stream.getTracks();return stream;};});
  await p.locator('#take-condition-photo').click();await p.waitForFunction(()=>document.querySelector('#return-camera').videoWidth>0);
  await p.locator('#capture-condition').click();await p.locator('#return-photo-status').filter({hasText:'Condition photo ready'}).waitFor();
  assert.equal(await p.evaluate(()=>window.conditionTestTracks.every(t=>t.readyState==='ended')),true,'camera is stopped after capture');
 }else{
  await p.evaluate(()=>{navigator.mediaDevices.getUserMedia=async()=>{throw new DOMException('Permission denied','NotAllowedError');};});
  await p.locator('#take-condition-photo').click();await p.locator('#return-photo-status').filter({hasText:'Camera permission was denied'}).waitFor();
  await p.locator('#return-form [name=photo]').setInputFiles({name:'unsupported.heic',mimeType:'image/heic',buffer:Buffer.from('unsupported image')});
  await p.locator('#return-photo-status').filter({hasText:'cannot open that image'}).waitFor();assert.equal(await p.locator('#return-form button.primary').isDisabled(),true);
  const bigPhoto={name:'large-camera.png',mimeType:'image/png',buffer:Buffer.concat([png,Buffer.alloc(9*1024*1024)])};
  await p.locator('#return-form [name=photo]').setInputFiles(bigPhoto);await p.locator('#return-photo-status').filter({hasText:'Condition photo ready'}).waitFor();
 }
 await p.locator('#return-condition-preview').waitFor();await p.locator('#return-form [name=note]').fill('Clean and working. Normal wear only.');
 await p.locator('#return-form button.primary').click();await p.getByText('Returned · owner inspection',{exact:true}).waitFor();
}

try{
 ownerPage=await page();renterPage=await page();
 await signup(ownerPage,'owner@fixture.invalid','Owner Neighbor','/garage');await ownerPage.getByRole('button',{name:'List a tool',exact:true}).first().click();await ownerPage.locator('#tool-photo').setInputFiles(photo);for(const[k,v]of Object.entries({title:'Community drill',description:'A cordless drill with charger.',condition:'Working, minor cosmetic wear.',rate:'10',deposit:'50'}))await ownerPage.locator('#lend-form [name='+k+']').fill(v);await ownerPage.locator('#listing-location').click();await ownerPage.waitForFunction(()=>document.querySelector('[name=lat]').value==='41.88');await ownerPage.getByRole('button',{name:'Publish listing',exact:true}).click();await ownerPage.getByRole('heading',{name:'Community drill',exact:true}).waitFor();
 const tool=(await backend.sql('select id,owner_id from public.tools where title=$1',['Community drill']))[0];await ownerPage.locator('[data-qr]').click();const qr=await ownerPage.getByRole('link',{name:'Open this item’s handoff page'}).getAttribute('href');assert.equal(qr,'https://neighborhoodgarage.net/#/handoff/'+tool.id);await ownerPage.locator('[data-close]').click();console.log('PASS owner profile, listing upload, GPS and permanent website item QR');
 await signup(renterPage,'renter@fixture.invalid','Renter Neighbor','/handoff/'+tool.id);assert.match(renterPage.url(),/handoff/);await renterPage.getByText('No authorized handoff is open for your account.',{exact:false}).waitFor();const renter=(await backend.sql('select id from public.profiles where display_name=$1',['Renter Neighbor']))[0].id;await backend.sql("insert into credit_ledger(user_id,amount_cents,reason,idempotency_key) values($1,10000,'fixture','fixture-wallet')",[renter]);
 const id=await request(renterPage,tool.id);assert.equal((await booking(id)).status,'requested');assert.equal(await balance(renter),10000);assert.equal(backend.stripeCalls(),0);await accept(ownerPage,id);assert.equal((await booking(id)).return_location.type,'owner_location');await plan(renterPage,id,true);await renterPage.getByText('Reserved · ready for pickup',{exact:true}).waitFor();assert.equal(await balance(renter),4000);assert.equal(backend.stripeCalls(),0);console.log('PASS request is uncharged, owner approval, private designated/GPS places and credit-only checkout');
 await open(renterPage,'/handoff/'+tool.id);await renterPage.locator('#pickup-form').waitFor();assert.equal((await booking(id)).status,'reserved');assert.equal(await renterPage.locator('#pickup-form [name=code]').inputValue(),tool.id);const directions=await renterPage.locator('#modal').getByRole('link',{name:'Google Maps ↗'}).getAttribute('href');assert.equal(new URL(directions).searchParams.get('destination'),'123 Main St, Chicago, front locker');await renterPage.locator('#pickup-form button.primary').click();await renterPage.getByText('With renter',{exact:true}).waitFor();assert.equal((await booking(id)).status,'out');
 await open(ownerPage,'/garage');await ownerPage.locator('.timeline-booking.status-out').waitFor();for(const width of [320,375,768,1280]){await ownerPage.setViewportSize({width,height:900});assert.equal(await ownerPage.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true,'calendar must scroll inside its wrapper');}await ownerPage.setViewportSize({width:375,height:812});await open(renterPage,'/');await renterPage.locator('[data-tool="'+tool.id+'"] .badge').filter({hasText:'Rented · expected back'}).waitFor();console.log('PASS same QR resolves pickup, directions, visible rented listing and mobile garage timeline');
 const future=await request(renterPage,tool.id,5);await accept(ownerPage,future);await plan(renterPage,future); // Wallet covers only part of this future booking.
 await renterPage.getByRole('button',{name:'Pay sandbox card'}).waitFor();await renterPage.getByRole('button',{name:'Pay sandbox card'}).click();await renterPage.getByText('Reserved · ready for pickup',{exact:true}).waitFor();assert.equal((await booking(future)).status,'reserved');await open(renterPage,'/rental/'+future);await renterPage.locator('[data-rental-action=cancel]').click();await renterPage.locator('#booking-confirm button.primary').click();await renterPage.getByText('Cancelled',{exact:true}).waitFor();console.log('PASS future follow-on booking and verified payment callback, cancellation returns credits');
 await open(renterPage,'/rental/'+id);await renterPage.locator('[data-rental-action=extension]').click();await renterPage.locator('#extension-form button.primary').click();await renterPage.locator('.extension-card').filter({hasText:'requested'}).waitFor();await open(ownerPage,'/rental/'+id);await ownerPage.locator('[data-rental-action=approve-extension]').click();await ownerPage.locator('#booking-confirm button.primary').click();await open(renterPage,'/rental/'+id);const providerCalls=backend.stripeCalls();await renterPage.locator('[data-rental-action=pay-extension]').click();await renterPage.locator('#extension-pay').getByText('Pay for extension',{exact:true}).click();await renterPage.locator('.extension-card').filter({hasText:'paid'}).waitFor();assert.equal(backend.stripeCalls(),providerCalls,'internal extension never initializes Stripe');assert.equal((await booking(id)).days,2);assert.equal((await booking(id)).deposit_cents,5000);console.log('PASS owner-approved extension is paid separately with existing deposit and no Stripe call for credits');
 await submitReturn(renterPage,tool.id);await open(ownerPage,'/rental/'+id);await ownerPage.locator('[data-rental-action=hold]').click();await ownerPage.locator('#booking-note textarea').fill('Checking the handle and original condition photos today.');await ownerPage.locator('#booking-note button.primary').click();await ownerPage.getByText('Returned · owner inspection',{exact:true}).waitFor();assert.equal((await booking(id)).status,'review');await ownerPage.locator('[data-rental-action=approve]').waitFor();await ownerPage.locator('[data-rental-action=received]').click();await ownerPage.locator('[data-rental-action=mark-ready]').waitFor();await ownerPage.locator('[data-rental-action=approve]').click();await ownerPage.locator('#booking-confirm button.primary').click();await ownerPage.getByText('Complete',{exact:true}).waitFor();assert.equal((await booking(id)).deposit_refunded_cents,5000);const settled=await booking(id);assert.equal(await balance(tool.owner_id),settled.owner_payout_cents-settled.rental_refunded_cents+settled.rental_fee_refunded_cents);assert(settled.rental_refunded_cents>0);assert.match(settled.return_photo_path,/\.jpg$/);console.log('PASS same QR return, photographed condition, held return remains actionable and full deposit release');
 const damage=await request(renterPage,tool.id);await accept(ownerPage,damage);await plan(renterPage,damage,true);await renterPage.getByText('Reserved · ready for pickup',{exact:true}).waitFor();await open(ownerPage,'/rental/'+damage);await ownerPage.locator('[data-rental-action=correct]').click();await ownerPage.locator('#correction-form [name=physicalState]').selectOption('out');await ownerPage.locator('#correction-form textarea').fill('Neighbor has collected the item but forgot to confirm.');await ownerPage.locator('#correction-form button.primary').click();await ownerPage.getByText('With renter',{exact:true}).waitFor();await submitReturn(renterPage,tool.id,true);await open(ownerPage,'/rental/'+damage);await ownerPage.locator('[data-rental-action=claim]').click();await ownerPage.locator('#claim-form [name=amount]').fill('5');await ownerPage.locator('#claim-form textarea').fill('Broken handle; replacement estimate is five dollars.');await ownerPage.locator('#claim-form [name=photo]').setInputFiles(photo);await ownerPage.locator('#claim-form button.primary').click();await ownerPage.getByText('Returned · deduction under review',{exact:true}).waitFor();assert.equal((await booking(damage)).deposit_refunded_cents,4500);await open(renterPage,'/rental/'+damage);await renterPage.locator('[data-rental-action=contest]').click();await renterPage.locator('#booking-note textarea').fill('The original condition photo shows this mark already.');await renterPage.locator('#booking-note button.primary').click();await renterPage.getByText('The renter contested this deduction.',{exact:false}).waitFor();assert((await booking(damage)).dispute_opened_at);await open(ownerPage,'/rental/'+damage);await ownerPage.locator('[data-rental-action=approve]').click();await ownerPage.locator('#booking-confirm button.primary').click();await ownerPage.getByText('Deposit settled · confirm receipt',{exact:true}).waitFor();assert.equal((await booking(damage)).deposit_refunded_cents,5000);await open(ownerPage,'/garage');await ownerPage.locator('[data-booking="'+damage+'"] [data-rental-action=received]').click();await ownerPage.locator('[data-booking="'+damage+'"] [data-rental-action=mark-ready]').click();await ownerPage.locator('[data-booking="'+damage+'"]').waitFor({state:'hidden'});assert.equal((await booking(damage)).status,'complete');assert.equal((await booking(damage)).physical_state,'ready');console.log('PASS physical correction audit, evidenced partial refund, renter contest and resolved remaining deposit');
 await open(renterPage,'/rental/'+id);await renterPage.locator('[data-rental-action=review]').click();await renterPage.locator('#review-form textarea').fill('Useful drill and clear pickup directions.');await renterPage.locator('#review-form button.primary').click();await renterPage.locator('dialog[open]').waitFor({state:'hidden'});await renterPage.getByRole('button',{name:'Profile',exact:true}).click();await renterPage.locator('#badges-tab').click();await renterPage.locator('.earned-badge.earned').filter({hasText:'Good neighbor'}).waitFor();await open(renterPage,'/messages?peer='+tool.owner_id);await renterPage.locator('[name=body]').fill('Thanks for the drill!');await renterPage.getByRole('button',{name:'Send',exact:true}).click();await renterPage.locator('.bubble.self').filter({hasText:'Thanks for the drill!'}).waitFor();await open(ownerPage,'/messages?peer='+renter);await ownerPage.locator('.bubble:not(.self)').filter({hasText:'Thanks for the drill!'}).waitFor();assert.deepEqual(errors,[]);console.log('PASS completed-rental review, earned badge, private two-party chat and no uncaught browser errors');
}catch(error){console.error('Browser journey failure:',error.message);for(const p of [ownerPage,renterPage])if(p)console.error(p.url(),(await p.locator('main').innerText()).slice(-1800),await p.locator('#toast').innerText());process.exitCode=1;}
finally{await browser.close();await new Promise(r=>server.close(r));await backend.db.close();}
