// Opt-in browser journey with fake transport. No real accounts or emails are created.
import {readFile} from 'node:fs/promises';
import {createServer} from 'node:http';
import {resolve,extname} from 'node:path';
import {chromium} from 'playwright';
import assert from 'node:assert/strict';
import QRCode from 'qrcode';
const output=process.env.NG_TEST_DIST||'dist-production';
const securityHeaders=Object.fromEntries((await readFile(output+'/_headers','utf8')).split('\n').slice(1).filter(line=>/^  [A-Za-z-]+:/.test(line)).map(line=>{const at=line.indexOf(':');return [line.slice(0,at).trim(),line.slice(at+1).trim()];}));
const server=createServer(async(req,res)=>{try{const name=new URL(req.url,'http://localhost').pathname;const path=resolve(output,'.'+(name==='/'?'/index.html':name));const data=await readFile(path);for(const [key,value]of Object.entries(securityHeaders))res.setHeader(key,value);res.setHeader('content-type',({'.js':'application/javascript','.css':'text/css','.svg':'image/svg+xml','.html':'text/html'})[extname(path)]||'text/plain');res.end(data)}catch{res.writeHead(404).end()}});
await new Promise(r=>server.listen(5173,'127.0.0.1',r));
const launch={headless:true};if(process.env.CHROMIUM_PATH){launch.executablePath=process.env.CHROMIUM_PATH;launch.args=['--disable-gpu'];}
const browser=await chromium.launch(launch),errors=[];
const me='00000000-0000-4000-8000-000000000001',owner='00000000-0000-4000-8000-000000000002',tool='00000000-0000-4000-8000-000000000003';
const jwt=Buffer.from(JSON.stringify({alg:'HS256',typ:'JWT'})).toString('base64url')+'.'+Buffer.from(JSON.stringify({sub:me,role:'authenticated',aal:'aal1',exp:Math.floor(Date.now()/1000)+3600})).toString('base64url')+'.'+Buffer.from('signature').toString('base64url');
const identity={id:me,email:'tester@example.net',app_metadata:{provider:'email',providers:['email']},user_metadata:{display_name:'Test Neighbor'},aud:'authenticated',created_at:new Date().toISOString(),email_confirmed_at:new Date().toISOString()};
const profile={id:me,display_name:'Test Neighbor',neighborhood:'',city:'',state:'',bio:'',stripe_onboarding_complete:false};
const listings=[{photo_path:me+'/ladder.png',id:'00000000-0000-4000-8000-000000000004',owner_id:me,title:'My ladder',category:'Home & DIY',description:'A ladder',condition:'Good',rate_cents:800,deposit_cents:2000,available:true,owner:{display_name:'Test Neighbor',neighborhood:'Oak Grove',city:'Chicago',stripe_onboarding_complete:false}},{id:tool,owner_id:owner,title:'Cordless drill',category:'Power tools',description:'A drill',condition:'Good',rate_cents:1200,deposit_cents:5000,available:true,owner:{display_name:'Helpful Owner',neighborhood:'Oak Grove',city:'Chicago',stripe_onboarding_complete:false}}];
for(const item of listings)item.created_at=new Date().toISOString();
const splitFilters=value=>{let depth=0,start=0;const out=[];for(let i=0;i<value.length;i++){if(value[i]==='(')depth++;if(value[i]===')')depth--;if(value[i]===','&&depth===0){out.push(value.slice(start,i));start=i+1;}}out.push(value.slice(start));return out;};
function matches(row,filter){if(/^(and|or)\(/.test(filter)){const parts=splitFilters(filter.slice(filter.indexOf('(')+1,-1)),results=parts.map(part=>matches(row,part));return filter.startsWith('and')?results.every(Boolean):results.some(Boolean);}let [key,op,...rest]=filter.split('.'),value=rest.join('.'),negative=false;if(op==='not'){negative=true;op=rest.shift();value=rest.join('.');}const actual=row[key];let result;if(op==='in')result=splitFilters(value.slice(1,-1)).includes(String(actual));else if(op==='is')result=value==='null'?actual==null:String(actual)===value;else if(op==='eq')result=String(actual)===value;else if(op==='neq')result=String(actual)!==value;else result=({gt:()=>actual>value,gte:()=>actual>=value,lt:()=>actual<value,lte:()=>actual<=value})[op]?.()??true;return negative?!result:result;}
function pageRows(rows,url){let data=rows.filter(row=>[...url.searchParams].every(([key,value])=>['select','order','limit','on_conflict'].includes(key)||matches(row,key==='or'?'or'+value:key+'.'+value)));const order=url.searchParams.get('order')?.split(',')||[];data.sort((a,b)=>{for(const term of order){const [key,dir]=term.split('.');const n=String(a[key]??'').localeCompare(String(b[key]??''));if(n)return dir==='desc'?-n:n;}return 0;});return data.slice(0,Number(url.searchParams.get('limit')||1000));}
const inbox=[],loans=[],ratings=[],wallet=[];let failMessage=true;const requests=[];let delayReputation=false,releaseReputation,markReputationStarted;const reputationStarted=new Promise(resolve=>markReputationStarted=resolve);const sockets=[];let pendingFactor=null;
try{
 const page=await browser.newPage({viewport:{width:375,height:812},geolocation:{latitude:41.88123,longitude:-87.63123},permissions:['geolocation'],hasTouch:true});page.on('pageerror',e=>errors.push(e.message));page.on('dialog',dialog=>{if(dialog.type()!=='prompt')dialog.accept();});const cspErrors=[];page.on('console',message=>{if(message.type()==='error'&&/Content Security Policy|violates.*directive/i.test(message.text()))cspErrors.push(message.text());});page.on('websocket',socket=>sockets.push(socket.url()));
 await page.routeWebSocket(/^wss:\/\/(ilfpugydxlzmmxjfrmrv|zbbespojxxoheavodtqs)\.supabase\.co\//,socket=>socket.close());
 await page.route(/^https:\/\/(ilfpugydxlzmmxjfrmrv|zbbespojxxoheavodtqs)\.supabase\.co\//,async route=>{
  const url=new URL(route.request().url()),p=url.pathname,method=route.request().method();let data={};requests.push({path:p,method,body:route.request().postData()});
  if(method==='GET'&&p.endsWith('/tool-photos/qa.png')){await route.fulfill({status:200,contentType:'image/png',body:Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII=','base64')});return;}
  if(p.endsWith('/auth/v1/signup'))data={user:identity,session:null};
  else if(p.endsWith('/auth/v1/token'))data={access_token:jwt,refresh_token:'mock-refresh',token_type:'bearer',expires_in:3600,expires_at:Math.floor(Date.now()/1000)+3600,user:identity};
  else if(p.endsWith('/auth/v1/user'))data=identity;
  else if(p.endsWith('/auth/v1/factors')){assert.equal(method,'POST');pendingFactor={id:'qa-factor',status:'unverified',factor_type:'totp'};data={...pendingFactor,totp:{qr_code:'<svg xmlns="http://www.w3.org/2000/svg"></svg>',secret:'QA-NONFUNCTIONAL-SECRET',uri:'otpauth://totp/qa'}};}
  else if(p.endsWith('/functions/v1/mfa-recovery'))data={pending:pendingFactor?[pendingFactor]:[]};
  else if(p.endsWith('/rest/v1/profiles')){if(method==='PATCH')Object.assign(profile,route.request().postDataJSON());data=profile;}
  else if(p.endsWith('/rest/v1/tools')){if(method==='PATCH'){const id=url.searchParams.get('id')?.replace('eq.','');const item=listings.find(t=>t.id===id);Object.assign(item,route.request().postDataJSON());data={id:item.id};}else if(method==='POST'){const item={...route.request().postDataJSON(),id:crypto.randomUUID(),tracking_code:'NGABC12345',created_at:new Date().toISOString(),owner:{display_name:profile.display_name}};listings.push(item);data={id:item.id};}else data=listings;}
  else if(p.endsWith('/rest/v1/rentals'))data=loans;
  else if(p.endsWith('/rest/v1/rental_extensions')||p.endsWith('/rest/v1/rental_events'))data=[];
  else if(p.endsWith('/rest/v1/messages')){if(method==='POST'){if(failMessage){failMessage=false;await route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({message:'Message service temporarily unavailable'})});return;}inbox.push({...route.request().postDataJSON(),id:crypto.randomUUID(),created_at:new Date().toISOString(),sender:{display_name:'Test Neighbor'},recipient:{display_name:'Helpful Owner'}});}data=inbox;}
  else if(p.endsWith('/rest/v1/reviews')){if(method==='POST'){ratings.push({...route.request().postDataJSON(),id:crypto.randomUUID(),tool_id:tool,subject_id:owner,subject_role:'owner',created_at:new Date().toISOString(),author:{display_name:'Test Neighbor'}});}data=ratings;}
  else if(p.endsWith('/rest/v1/credit_ledger'))data=wallet;
  else if(p.endsWith('/rest/v1/rpc/release_version'))data='2026-10-04-hardening-1';
  else if(p.endsWith('/rest/v1/rpc/search_tools')){const args=route.request().postDataJSON();data=listings.filter(t=>t.owner_id!==me&&t.available&&!t.archived_at&&(!args.p_after||t.id>args.p_after)).sort((a,b)=>a.id.localeCompare(b.id)).slice(0,args.p_limit);}
  else if(p.endsWith('/functions/v1/upload-photo'))data={path:me+'/'+(loans[0]?.id||'fixture')+'/'+crypto.randomUUID()+'.jpg'};
  else if(p.endsWith('/rest/v1/rpc/wallet_summary'))data={balance_cents:wallet.reduce((sum,e)=>sum+e.amount_cents,0),total_in_cents:wallet.reduce((sum,e)=>sum+Math.max(0,e.amount_cents),0),total_out_cents:-wallet.reduce((sum,e)=>sum+Math.min(0,e.amount_cents),0),entry_count:wallet.length,pending_withdrawal_cents:0,dispute_hold:false};
  else if(p.endsWith('/functions/v1/rental-booking')){const body=route.request().postDataJSON();if(body.action==='availability')data={availability:listings.map(t=>({tool_id:t.id,rented:false,inspection_pending:false,booked_ranges:[]})),processed:0};else if(body.action==='request'){const loan={id:crypto.randomUUID(),tool_id:body.toolId,owner_id:owner,renter_id:me,status:'requested',physical_state:'ready',created_at:new Date().toISOString(),days:1,daily_rate_cents:1200,rental_cents:1200,deposit_cents:5000,deposit_refunded_cents:0,starts_at:body.pickupStart,pickup_window_start:body.pickupStart,pickup_window_end:body.pickupEnd,return_window_start:body.returnStart,return_window_end:body.returnEnd,calendar_ends_at:body.returnEnd,tool:{...listings[1],tracking_code:'NG1234ABCD'}};loans.push(loan);data={rental:loan};}}
  else if(p.endsWith('/functions/v1/create-checkout')){const body=route.request().postDataJSON();const loan=loans.find(x=>x.id===body.rentalId);assert.equal(loan.status,'accepted');if(body.action==='quote')data={principalCents:0,processingFeeCents:0,totalCents:0};else{loan.status='reserved';data={reserved:true};}}
  else if(p.endsWith('/functions/v1/rental-action')){const body=route.request().postDataJSON(),loan=loans.find(x=>x.id===body.rentalId);if(body.action==='schedule')loan.scheduled_pickup_at=body.pickupAt;if(body.action==='pickup'){if(body.code!=='NG1234ABCD'){await route.fulfill({status:400,contentType:'application/json',body:JSON.stringify({error:'Tracking code does not match',requestId:'qa-reference'})});return;}loan.status='out';loan.physical_state='out';}if(body.action==='return'){loan.status='review';loan.physical_state='return_reported';assert.equal(body.handoffMethod,'dropoff');assert(body.returnPhotoPath.startsWith(me+'/'));}if(body.action==='approve'){loan.status='complete';loan.physical_state='ready';loan.physical_returned_at=new Date().toISOString();loan.item_ready=true;loan.payout_status='pending';data={payoutWarning:'Deposit credits returned. Owner payout is pending.'};}if(body.action==='retry-payout')loan.payout_status='paid';}
  else if(p.endsWith('/functions/v1/delete-account')){await route.fulfill({status:409,contentType:'application/json',body:JSON.stringify({error:'Finish or cancel active rentals before deleting your account.'})});return;}
  else if(p.endsWith('/functions/v1/connect-account')){await route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({error:'Stripe sandbox temporarily unavailable. Please retry.',requestId:'qa-stripe'})});return;}
  else if(p.endsWith('/rest/v1/rpc/reputation_summary'))data=[{user_id:me,listed:1,borrowed:3,lent:1,review_count:0,rating:0},{user_id:owner,listed:3,borrowed:0,lent:10,review_count:10,rating:4.9,owner_review_count:10,owner_rating:4.9,owner_reviewers:5}];
  else if(p.includes('/storage/v1/object/sign/'))data={signedURL:'/object/sign/tool-photos/qa.png?token=fixture'};
  else if(p.includes('/storage/v1/'))data={Key:'qa'};
  if(Array.isArray(data)&&p.startsWith('/rest/v1/')&&!p.includes('/rpc/'))data=pageRows(data,url);
  if(delayReputation&&p.endsWith('/rest/v1/rpc/reputation_summary')){markReputationStarted();await new Promise(resolve=>releaseReputation=resolve);}
  await route.fulfill({status:200,contentType:'application/json',body:JSON.stringify(data)});
 });
 await page.goto('http://127.0.0.1:5173/');
 await page.locator('[data-auth-tab=signup]').click();await page.locator('#signup [name=displayName]').fill('Test Neighbor');await page.locator('#signup [name=email]').fill('tester@example.net');await page.locator('#signup [name=password]').fill('sample-password-123');await page.locator('#signup button.primary').click();await page.locator('#auth-notice:not(.hidden)').waitFor();assert.match(await page.locator('#auth-notice').textContent(),/confirmation link/);console.log('PASS pending email confirmation is explicit');
 await page.locator('#signin [name=password]').fill('sample-password-123');await page.locator('#signin button.primary').click();await page.locator('#profile-form').waitFor();for(const [name,value] of Object.entries({neighborhood:'Oak Grove',city:'Chicago',state:'IL',bio:'Testing tool sharing'}))await page.locator(`#profile-form [name=${name}]`).fill(value);await page.getByRole('button',{name:'Finish setup',exact:true}).click();await page.locator('.topbar').waitFor({timeout:10000}).catch(async e=>{console.log('DEBUG',await page.locator('#toast').textContent(),(await page.locator('main').innerText()).slice(0,500));throw e});console.log('PASS sign-in renders without a reload');
 await page.getByRole('button',{name:'Profile',exact:true}).click();await page.locator('#account-tab').waitFor();await page.locator('#delete-account').click();await page.locator('#delete-account-form [name=password]').fill('sample-password-123');await page.locator('#delete-account-form [name=confirmation]').fill('DELETE');await page.locator('#delete-account-form button').click();await page.locator('#delete-account-status').filter({hasText:'active rentals'}).waitFor();await page.locator('[data-close]').click();console.log('PASS permanent deletion confirmation and blocked-rental explanation');
 await page.locator('#manage-mfa').click();await page.locator('#enable-mfa').waitFor();await page.evaluate(()=>{window.dispatchEvent(new Event('blur'));window.dispatchEvent(new Event('focus'));document.dispatchEvent(new Event('visibilitychange'));});await page.locator('#enable-mfa').waitFor();await page.locator('[data-close]').click();await page.locator('#manage-mfa').click();await page.locator('#resume-mfa').waitFor();assert.equal(requests.filter(r=>r.path.endsWith('/auth/v1/factors')&&r.method==='POST').length,1);await page.locator('[data-close]').click();console.log('PASS optional MFA survives focus changes and resumes the existing factor');
 await page.locator('#badges-tab').click();await page.locator('#profile-badges:not(.hidden)').waitFor();assert(await page.locator('.earned-badge.earned').count()>=1);console.log('PASS badge tab and milestone progress');
 await page.getByRole('link',{name:'See what neighbors see'}).click();await page.getByRole('heading',{name:'Earned badges'}).waitFor();console.log('PASS neighbor-facing badges');
 await page.getByRole('link',{name:'Explore',exact:true}).click();await page.getByRole('heading',{name:'Big plans. Neighborly prices.'}).waitFor();await page.locator('.tool-card .badge-tag').waitFor();assert.match(await page.locator('.tool-card .badge-tag').textContent(),/Neighborhood favorite/);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await page.locator('.tool-card .trust-tag[aria-label="Silver owner trust tier"]').waitFor();console.log('PASS owner trust star and earned badge on mobile tool card');

 for(const width of [320,375,768,1280]){await page.setViewportSize({width,height:812});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));}await page.setViewportSize({width:375,height:812});console.log('PASS responsive navigation at 320, 375, 768 and 1280 pixels');
 listings[1].approximate_lat=41.88;listings[1].approximate_lng=-87.63;
 await page.reload();await page.locator('#locate').click();await page.locator('#location-status').filter({hasText:'Location found'}).waitFor();await page.locator('#radius').selectOption('2');await page.locator('#map-view').click();await page.locator('.leaflet-interactive').first().waitFor();assert.equal(await page.locator('.my-location-dot').count(),1);assert.equal(await page.locator('.tool-map-marker').count(),1);await page.locator('.tool-map-marker').click();await page.locator('.tool-map-popup').filter({hasText:'Cordless drill'}).waitFor();await page.locator('.leaflet-popup-close-button').click();console.log('PASS GPS, nearby radius, tool map and private position marker');
 await page.locator('[data-tool]').click();await page.locator('#quote').filter({hasText:'$62.00'}).waitFor();assert.match(await page.locator('.deposit-note').innerText(),/not an automatic card refund/);
 await page.locator('#message-owner').click();await page.locator('[name=body]').fill('Can I collect this Saturday?');await page.getByRole('button',{name:'Send',exact:true}).click();await page.locator('#toast').filter({hasText:'temporarily unavailable'}).waitFor();assert.equal(await page.locator('[name=body]').inputValue(),'Can I collect this Saturday?');await page.getByRole('button',{name:'Send',exact:true}).click();await page.locator('.bubble.self').waitFor();assert.equal(inbox.length,1);
 await page.locator('[name=body]').fill('Keep my unsent draft');await page.getByRole('link',{name:'Explore',exact:true}).click();await page.getByRole('link',{name:'Messages',exact:true}).click();assert.equal(await page.locator('[name=body]').inputValue(),'Keep my unsent draft');console.log('PASS chat failure, retry, delivery display and draft preservation across routes');
 await page.getByRole('link',{name:'Explore',exact:true}).click();await page.locator('[data-tool]').click();await page.locator('#reserve').click();await page.getByText('Awaiting owner approval',{exact:true}).waitFor();assert.equal(loans[0].status,'requested');assert.equal(requests.filter(r=>r.path.endsWith('/functions/v1/create-checkout')).length,0);loans[0].status='accepted';loans[0].expires_at=new Date(Date.now()+86400000).toISOString();loans[0].pickup_location={type:'place',label:'Owner porch',address:'123 Main St, Chicago'};loans[0].return_location=loans[0].pickup_location;await page.reload();await page.locator('[data-rental-action=plan]').click();await page.locator('#pickup-plan button.primary').click();await page.locator('[data-rental-action=pickup]').click();await page.locator('#pickup-form [name=code]').fill('NG00000000');await page.locator('#pickup-form button.primary').click();await page.locator('#toast').filter({hasText:'qa-reference'}).waitFor();await page.locator('#pickup-form [name=code]').fill('NG1234ABCD');await page.locator('#pickup-form button.primary').click();await page.locator('[data-rental-action=return]').click();
 const photo={name:'qa-tool.png',mimeType:'image/png',buffer:Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII=','base64')};
 await page.locator('#return-form [name=photo]').setInputFiles(photo);await page.locator('#return-form [name=handoff]').selectOption('dropoff');await page.locator('#return-form [name=note]').fill('Clean, normal wear only');await page.locator('#return-form button.primary').click();await page.getByText('Returned · owner inspection',{exact:true}).waitFor();console.log('PASS rental UI, actionable non-2xx error, pickup and photographed drop-off');
 // Model an owner concurrence response; financial invariants are tested separately in live SQL.
 loans[0].status='complete';loans[0].physical_state='ready';loans[0].item_ready=true;loans[0].physical_returned_at=new Date().toISOString();wallet.push({amount_cents:5000});await page.reload();await page.locator('[data-rental-action=review]').click();await page.locator('#review-form [name=body]').fill('Great tool and helpful neighbor');await page.locator('#review-form button.primary').click();await page.locator('dialog[open]').waitFor({state:'hidden'});assert.equal(ratings.length,1);await page.getByRole('link',{name:'Explore',exact:true}).click();await page.locator('[data-tool]').click();await page.getByText('Great tool and helpful neighbor',{exact:true}).waitFor();console.log('PASS post-return review appears on tool detail');
 await page.getByRole('button',{name:'Profile',exact:true}).click();await page.locator('#account-tab').waitFor();await page.getByText('$50.00',{exact:true}).first().waitFor();await page.locator('#start-payouts').click();await page.locator('#toast').filter({hasText:'qa-stripe'}).waitFor();console.log('PASS deposit credit display and readable Stripe service failure');
 await page.getByRole('link',{name:'My garage',exact:true}).click();
 for(const width of [375,1280]){
  await page.setViewportSize({width,height:900});
  const preview=page.getByRole('button',{name:'View listing details for My ladder',exact:true});
  assert.equal(await preview.locator('img').evaluate(img=>getComputedStyle(img).objectFit),'cover');
  assert.equal(await preview.locator('img').evaluate(img=>getComputedStyle(img).objectPosition),'50% 50%');
  if(width===375)await preview.tap();else await preview.click();
  await page.locator('#modal').getByRole('heading',{name:'My ladder',exact:true}).waitFor();
  await page.getByRole('button',{name:'Zoom in',exact:true}).click();
  assert.equal(await page.locator('#listing-photo-zoom').getAttribute('aria-pressed'),'true');
  assert.equal(await page.locator('#listing-photo-viewport').evaluate(el=>el.scrollWidth>el.clientWidth),true);
  await page.getByRole('button',{name:'Fit photo',exact:true}).click();
  assert.equal(await page.locator('#listing-photo-zoom').getAttribute('aria-pressed'),'false');
  await page.getByRole('button',{name:'Close listing details',exact:true}).click();
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
 }
 await page.setViewportSize({width:375,height:812});
 console.log('PASS centered full garage photo, one-tap/click details and zoom at mobile/desktop widths');
 await page.getByRole('link',{name:'My garage',exact:true}).click();loans.push({...loans[0],id:crypto.randomUUID(),owner_id:me,renter_id:owner,tool_id:listings[0].id,status:'review',deposit_cents:2000,deposit_refunded_cents:0,owner_payout_cents:760,review_deadline:new Date(Date.now()+86400000).toISOString(),tool:{title:'My ladder'},assessment:{source:'manual',renterNote:'Returned clean'}});await page.reload();await page.locator('[data-rental-action=approve]').click();await page.locator('#booking-confirm [name=confirmReceipt]').check();await page.locator('#booking-confirm button.primary').click();await page.locator('[data-payout]').waitFor();await page.locator('[data-payout]').click();await page.getByRole('heading',{name:'Pending payouts'}).waitFor({state:'hidden'});console.log('PASS owner concurrence and pending-payout retry interface');
 await page.getByRole('link',{name:'My garage',exact:true}).click();await page.locator('[data-edit]').click();await page.locator('#lend-form [name=title]').fill('Updated ladder');await page.getByRole('button',{name:'Save changes',exact:true}).click();await page.locator('.tool-card h3',{hasText:'Updated ladder'}).waitFor();assert.equal(listings[0].title,'Updated ladder');console.log('PASS owner edits without uploading another photo');
 await page.locator('[data-remove]').click();await page.locator('#confirm-remove').click();await page.getByRole('heading',{name:'Your garage is empty'}).waitFor();assert.equal(listings[0].available,false);assert(listings[0].archived_at);console.log('PASS removal hides current listing and pauses availability');
 await page.getByRole('link',{name:'View removed listings'}).click();await page.locator('[data-restore]').click();await page.getByRole('heading',{name:'No removed listings'}).waitFor();assert.equal(listings[0].archived_at,null);assert.equal(listings[0].available,false);await page.getByRole('button',{name:'Paused',exact:true}).click();await page.getByRole('heading',{name:'Paused listings',exact:true}).waitFor();await page.locator('.garage-card').waitFor();assert.equal(await page.locator('#garage-calendar,.booking-card').count(),0);await page.getByRole('button',{name:'Active',exact:true}).click();await page.getByRole('heading',{name:'Your garage is empty'}).waitFor();assert.equal(await page.locator('.garage-card').count(),0);console.log('PASS restore remains paused and separate from active garage');

 await page.getByRole('button',{name:'List a tool',exact:true}).first().click();await page.locator('#tool-photo').setInputFiles(photo);await page.locator('#photo-preview:not(.hidden)').waitFor();
 await page.locator('#clean-photo').click();await page.locator('#ai-status').filter({hasText:'Could not separate'}).waitFor();
 // A real local OCR worker reads the fixture. Block remote visual weights to verify the label fallback.
 await page.route(/https:\/\/(tfhub.dev|storage.googleapis.com)\//,route=>route.abort());
 const scanNetworkStart=requests.length;
 const label={name:'label.png',mimeType:'image/png',buffer:await readFile(process.env.NG_LABEL_FIXTURE||'tests/fixtures/tool-label.png')};
 await page.locator('#label-photo').setInputFiles(label);await page.locator('#identify-tool').click();
 await page.locator('#scan-suggestion:not(.hidden)').waitFor({timeout:75000});
 assert.equal(await page.locator('#lend-form [name=title]').inputValue(),'DEWALT Power drill');
 assert.match(await page.locator('#lend-form [name=description]').inputValue(),/DCD771/);
 assert.equal(await page.locator('#lend-form [name=condition]').inputValue(),'');
 assert.equal(await page.locator('#lend-form [name=rate]').inputValue(),'');
 assert.equal(await page.locator('#lend-form [name=deposit]').inputValue(),'');
 await page.locator('#lend-form [name=description]').fill('My own description.');
 await page.locator('#lend-form [name=category]').selectOption('Home & DIY');
 await page.locator('#identify-tool').click();await page.getByRole('button',{name:'Use suggested description',exact:true}).waitFor({timeout:75000});
 assert.equal(await page.locator('#lend-form [name=description]').inputValue(),'My own description.');
 assert.equal(await page.locator('#lend-form [name=category]').inputValue(),'Home & DIY');
 await page.getByRole('button',{name:'Use suggested description',exact:true}).click();
 assert.match(await page.locator('#lend-form [name=description]').inputValue(),/DCD771/);
 // Decode an actual QR image with the bundled fallback, even on native-capable browsers.
 await page.evaluate(()=>Object.defineProperty(window,'BarcodeDetector',{configurable:true,value:undefined}));
 const barcode='https://www.dewalt.com/product/dcd771/drill';
 await page.locator('#label-photo').setInputFiles({name:'barcode.png',mimeType:'image/png',buffer:await QRCode.toBuffer(barcode,{width:400,margin:4})});
 await page.locator('#identify-tool').click();await page.locator('#scan-suggestion:not(.hidden)').waitFor({timeout:75000});
 assert.match(await page.locator('#scan-suggestion .tracking').innerText(),/https:\/\/www\.dewalt\.com\/product\/dcd771\/drill/);
 await page.locator('#scan-suggestion').getByText('DEWALT',{exact:true}).waitFor();
 console.log('PASS production browser bundle decodes a branded QR photo without native barcode support');
 assert.equal(requests.slice(scanNetworkStart).some(r=>r.method==='POST'&&/\/storage\/v1\/object\/(tool-photos|return-photos)\//.test(r.path)),false,'identification does not upload scan photos');
 assert.equal(requests.slice(scanNetworkStart).some(r=>r.path.endsWith('/functions/v1/identify-tool')),false,'identification does not call a remote AI function');
 console.log('PASS real browser OCR, description/brand/model suggestions, manual edits preserved, explicit acceptance and no scan upload');
 for(const [name,value] of Object.entries({title:'New test sander',description:'A useful sander',condition:'Normal cosmetic wear',rate:'12',deposit:'75'}))await page.locator(`#lend-form [name=${name}]`).fill(value);
 await page.locator('#listing-location').click();await page.waitForFunction(()=>document.querySelector('[name=lat]').value==='41.88');assert.match(await page.locator('#profit-preview').innerText(),/11.40/);await page.getByRole('button',{name:'Publish listing',exact:true}).click();await page.getByRole('heading',{name:'New test sander',exact:true}).waitFor();assert.equal(listings.at(-1).approximate_lng,-87.63);assert(listings.at(-1).baseline_photo_path.startsWith(me+'/'));await page.getByRole('button',{name:'Tracking code for New test sander'}).click();await page.locator('dialog img.qr').waitFor();await page.locator('[data-close]').click();console.log('PASS photo fallback, new listing upload, rounded GPS, earnings and QR code');
 await page.getByRole('link',{name:'Explore',exact:true}).click();
 await page.evaluate(()=>{navigator.geolocation.getCurrentPosition=callback=>{window.completeLocation=()=>callback({coords:{latitude:41.88,longitude:-87.63}});};});
 await page.locator('#locate').click();await page.waitForFunction(()=>typeof window.completeLocation==='function');await page.getByRole('button',{name:'Profile',exact:true}).click();await page.locator('#account-tab').waitFor();await page.evaluate(()=>window.completeLocation());await page.waitForTimeout(100);assert.deepEqual(errors,[],'navigation during GPS lookup must not crash');console.log('PASS navigating away during GPS lookup');
 await page.getByRole('button',{name:'Profile',exact:true}).click();delayReputation=true;await page.locator('#edit-profile button.primary').click();await reputationStarted;await page.locator('#signout').click();await page.locator('#signin').waitFor();const socketCount=sockets.length;releaseReputation();await page.waitForTimeout(200);assert.equal(sockets.length,socketCount,'late account load must not reopen realtime after logout');assert.deepEqual(errors,[]);await page.reload();await page.locator('#signin').waitFor();assert.equal(await page.locator('.topbar').count(),0);await page.goto('http://127.0.0.1:5173/#error=access_denied&error_description=Email%20link%20has%20expired');await page.reload();await page.locator('#auth-notice').filter({hasText:'Email link has expired'}).waitFor();page.once('dialog',dialog=>dialog.accept('tester@example.net'));await page.locator('#reset-password').click();await page.locator('#toast').filter({hasText:'Password reset email sent'}).waitFor();assert(requests.some(r=>r.path.endsWith('/auth/v1/recover')));console.log('PASS expired email-link guidance and password-reset request');assert(requests.some(r=>r.path.endsWith('/signup')&&JSON.parse(r.body).email));console.log('PASS sign-out clears session and survives reload');
 assert.deepEqual(errors,[]);assert.deepEqual(cspErrors,[],'production CSP must allow exercised maps, OCR and QR workers');console.log('PASS production CSP and no uncaught browser errors');
}finally{await browser.close();server.close()}
