export const FEE = .05;
export const money = n => new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(n);
export const quote = (tool,days,credits=0) => { const rental=Math.round(tool.rate*days*100)/100, fee=Math.round(rental*FEE*100)/100, total=rental+tool.deposit; return {rental,fee,owner:rental-fee,deposit:tool.deposit,total,credits:Math.min(credits,total),due:Math.max(0,total-credits)}; };
const seed=()=>({credits:120,tools:[
{id:'NG1001',title:'20V cordless drill kit',category:'Power tools',rate:8,deposit:65,owner:'Alex M.',rating:4.9,lat:41.884,lng:-87.632,icon:'🛠️',color:'mint',description:'Your weekend-project sidekick. Includes two batteries, charger, and a 30-piece bit set.',condition:'Light cosmetic marks on grip; fully functional.'},
{id:'NG1002',title:'Electric pressure washer',category:'Outdoor',rate:18,deposit:120,owner:'Jamie R.',rating:5,lat:41.88,lng:-87.63,icon:'💦',color:'blue',description:'Give the patio a fresh start. Includes hose and three spray nozzles.',condition:'Minor scratches on housing.'},
{id:'NG1003',title:'6-foot folding ladder',category:'Home & DIY',rate:7,deposit:55,owner:'Morgan T.',rating:4.8,lat:41.89,lng:-87.64,icon:'🪜',color:'peach',description:'A sturdy fiberglass ladder for all those just-out-of-reach jobs.',condition:'Paint spots on steps; hinges intact.'},
{id:'NG1004',title:'Random orbital sander',category:'Power tools',rate:9,deposit:70,owner:'Sam K.',rating:4.9,lat:41.875,lng:-87.625,icon:'🪵',color:'yellow',description:'Smooth out your next furniture project. Dust bag included; bring your own sanding discs.',condition:'Normal wear on sanding pad.'},
{id:'NG1005',title:'Garden hand tool set',category:'Garden',rate:5,deposit:30,owner:'Casey L.',rating:5,lat:41.886,lng:-87.62,icon:'🌱',color:'mint',description:'Trowel, cultivator, and pruning shears for a happy little garden.',condition:'Clean with light soil staining.'},
{id:'NG1006',title:'Heavy-duty hand truck',category:'Home & DIY',rate:12,deposit:80,owner:'Jordan P.',rating:4.9,lat:41.879,lng:-87.642,icon:'📦',color:'peach',description:'Make moving day a little lighter. Includes a tie-down strap.',condition:'Scuffed platform; tires in good condition.'}],rentals:[],messages:[{id:'welcome',peer:'Alex M.',from:'Alex M.',text:'Hi neighbor! Happy to help coordinate a pickup. What time works for you?',time:Date.now()}],reviews:[]});
export class DemoEngine {
 constructor(storage){this.storage=storage;this.key='ng-demo-v1';try {this.data=JSON.parse(storage.getItem(this.key))||seed();}catch{this.data=seed();}}
 save(){this.storage.setItem(this.key,JSON.stringify(this.data));}
 async state(){try{this.data=JSON.parse(this.storage.getItem(this.key))||this.data;}catch{}return structuredClone(this.data);}
 async listTool(t){if(!t.title?.trim()||!(t.rate>0)||!(t.deposit>=0))throw Error('Add a title and valid prices.');const tool={...t,id:'NG'+Date.now(),owner:'You',rating:5,lat:41.883,lng:-87.635};this.data.tools.push(tool);this.save();return tool;}
 async scan(photo,scenario='normal'){if(!photo)throw Error('Add a photo first.');return {title:'20V cordless drill kit',category:'Power tools',deposit:65,condition:scenario==='damage'?'Possible structural damage; owner review required.':'Normal cosmetic wear; no structural damage in simulated result.',damage:scenario==='damage',part:'DEMO-20V',serial:'Unverified — review manually',background:'Preview simulated; original photo retained'};}
 async reserve(toolId,days){await this.state();const t=this.data.tools.find(t=>t.id===toolId);if(!t||t.owner==='You')throw Error('Choose a neighbor’s tool.');if(!Number.isInteger(days)||days<1||days>30)throw Error('Choose 1–30 days.');if(this.data.rentals.some(r=>r.toolId===toolId&&!['complete','cancelled'].includes(r.status)))throw Error('This tool is already reserved.');const q=quote(t,days,this.data.credits);this.data.credits-=q.credits;const r={id:crypto.randomUUID(),toolId,days,...q,status:'reserved',created:Date.now()};this.data.rentals.push(r);this.save();return r;}
 async transition(id,action,payload={}){await this.state();const r=this.data.rentals.find(r=>r.id===id);if(!r)throw Error('Rental not found.');if(action==='pickup'&&r.status==='reserved'){if(payload.code!==r.toolId)throw Error('That tracking code does not match this tool.');r.status='out';}else if(action==='return'&&r.status==='out'){if(!payload.photo)throw Error('A return photo is required.');if(payload.method!=='dropoff'&&payload.code!==r.toolId)throw Error('Tracking code does not match.');r.status='review';r.assessment=payload.assessment;r.returnPhoto=payload.photo;r.method=payload.method;}else if(action==='approve'&&r.status==='review'){r.status='complete';this.data.credits+=r.deposit;}else if(action==='dispute'&&r.status==='review'){r.status='disputed';}else throw Error('This action is not available for this rental.');this.save();return r;}
 async message(peer,text){if(!text.trim()||text.length>2000)throw Error('Enter a message up to 2,000 characters.');this.data.messages.push({id:crypto.randomUUID(),peer,from:'You',text:text.trim(),time:Date.now()});this.save();}
 async review(id,rating,text){const r=this.data.rentals.find(r=>r.id===id);if(!r||r.status!=='complete'||this.data.reviews.some(v=>v.rentalId===id))throw Error('Review unavailable.');if(!(rating>=1&&rating<=5))throw Error('Choose a rating.');this.data.reviews.push({rentalId:id,rating,text});this.save();}
}
export class LiveEngine {
 constructor(base){this.base=base;}
 async request(path,method='GET',body){if(!this.base)throw Error('Live mode needs a backend. Set window.NG_API_BASE in config.js and deploy the API described in backend/README.md.');const url=new URL(this.base);if(url.protocol!=='https:'&&url.hostname!=='localhost')throw Error('Live API requires HTTPS.');const r=await fetch(this.base.replace(/\/$/,'')+path,{method,credentials:'include',headers:{'Content-Type':'application/json','X-NG-Request':'web'},body:body?JSON.stringify(body):undefined});if(!r.ok)throw Error(`Live request failed (${r.status}). Please try again.`);return r.json();}
 state(){return this.request('/state');} listTool(t){return this.request('/tools','POST',t);} scan(photo,scenario){return this.request('/scans','POST',{photo,scenario});} reserve(toolId,days){return this.request('/rentals','POST',{toolId,days,idempotencyKey:crypto.randomUUID()});} transition(id,action,payload){return this.request(`/rentals/${encodeURIComponent(id)}/${action}`,'POST',payload||{});} message(peer,text){return this.request('/messages','POST',{peer,text});} review(id,rating,text){return this.request(`/rentals/${encodeURIComponent(id)}/reviews`,'POST',{rating,text});}
}
export function distance(a,b){const r=Math.PI/180,dlat=(b.lat-a.lat)*r,dlng=(b.lng-a.lng)*r;return 3958.8*2*Math.asin(Math.sqrt(Math.sin(dlat/2)**2+Math.cos(a.lat*r)*Math.cos(b.lat*r)*Math.sin(dlng/2)**2));}
// Code 39 encodes the tracking ID; start/stop sentinels and quiet zones included.
export function barcode(code){const patterns={'0':'nnnwwnwnn','1':'wnnwnnnnw','2':'nnwwnnnnw','3':'wnwwnnnnn','4':'nnnwwnnnw','5':'wnnwwnnnn','6':'nnwwwnnnn','7':'nnnwnnwnw','8':'wnnwnnwnn','9':'nnwwnnwnn','N':'nnnnwnnww','G':'nnnnnwwnw','*':'nwnnwnwnn'};let x=16,rects='';for(const c of '*'+code+'*'){if(!patterns[c])throw Error('Unsupported tracking code');[...patterns[c]].forEach((p,i)=>{let w=p==='w'?3:1;if(i%2===0)rects+=`<rect x="${x}" y="5" width="${w}" height="48"/>`;x+=w;});x+=1;}return `<svg role="img" aria-label="Tracking barcode ${code}" viewBox="0 0 ${x+16} 60" xmlns="http://www.w3.org/2000/svg">${rects}</svg>`;}
