import {esc} from './core.js';
export async function renderSupport(root,o){
 root.innerHTML='<h1>Support & notifications</h1><p>For an emergency, contact local emergency services. This queue is not emergency assistance.</p><p role="status">Loading…</p>';
 try{
 const data=await o.invoke('support',{action:'list'});if(!root.isConnected)return;
 root.innerHTML=`<h1>Support & notifications</h1><p>For an emergency, contact local emergency services. For rental or payment problems, open a case below. Case deadlines are targets, not a promise of immediate response.</p><h2>Notifications</h2><div id="notices">${data.notifications.map(n=>`<p>${esc(n.message)} ${n.rental_id?`<a href="#/rental/${n.rental_id}">Open rental</a>`:''}</p>`).join('')||'<p>No notifications.</p>'}</div><form id="support-report" class="form-card"><h2>Open a case</h2><label>Rental reference (optional)<input name="rentalId" placeholder="Rental ID from your receipt"></label><label>Reason<select name="kind">${['payment','not_received','damage','safety','abuse','withdrawal','deletion'].map(k=>`<option value="${k}">${esc(k.replaceAll('_',' '))}</option>`).join('')}</select></label><label>What happened?<textarea name="description" minlength="10" maxlength="3000" required></textarea></label><button class="primary">Submit case</button><p role="status" id="case-status"></p></form><h2>${data.operator?'Operator queue':'Your cases'}</h2><div id="case-list"></div><button id="cases-more">Load older cases</button>`;
 const add=cases=>{for(const c of cases){const el=document.createElement('article');el.className='panel';el.innerHTML=`<h3>${esc(c.kind.replaceAll('_',' '))} · ${esc(c.status)}</h3><p>${esc(c.description)}</p><p>${esc(c.resolution)}</p><p class="fine">Case ${c.id} · target response ${esc(new Date(c.due_at).toLocaleString())}${c.assigned_to?' · Assigned':''}</p>${c.rental_id?`<a href="#/rental/${c.rental_id}">Rental reference</a>`:''}${data.operator?`<button data-evidence="${c.id}">View case evidence</button><div data-evidence-panel="${c.id}"></div><form data-case="${c.id}" class="stack"><label>Action<select name="operation"><option value="assign">Assign to me</option><option value="confirm-receipt">Confirm physical receipt</option><option value="settle-return">Settle return</option><option value="allocate-payment-loss">Allocate verified payment loss to owner earnings</option><option value="resolve">Resolve case / release case hold</option><option value="restrict-account">Restrict subject account</option><option value="restore-account">Restore subject account</option></select></label><label>Amount ($; agreed damage or verified payment loss allocation)<input name="amount" type="number" min="0" step="0.01" value="0"></label><label>Decision and supporting evidence<textarea name="note" minlength="10" maxlength="3000" required></textarea></label><button>Record audited decision</button></form>`:''}`;root.querySelector('#case-list').append(el);}
 root.querySelectorAll('[data-evidence]').forEach(b=>b.onclick=async()=>{b.disabled=true;try{const d=await o.invoke('support',{action:'details',caseId:b.dataset.evidence});const panel=root.querySelector(`[data-evidence-panel="${b.dataset.evidence}"]`);panel.innerHTML=`<pre class="case-evidence">${esc(JSON.stringify(d.rental,null,2))}</pre>${d.photos.map(url=>`<a href="${esc(url)}" target="_blank" rel="noopener">Open condition evidence (expires in 5 minutes)</a>`).join('<br>')}`;}catch(e){o.toast(e.message);}finally{b.disabled=false;}});
 root.querySelectorAll('[data-case]').forEach(f=>f.onsubmit=async e=>{e.preventDefault();const b=e.submitter;b.disabled=true;try{const v=Object.fromEntries(new FormData(f));await o.invoke('support',{action:'operate',caseId:f.dataset.case,operation:v.operation,note:v.note,amountCents:Math.round(Number(v.amount)*100),requestId:crypto.randomUUID()});await renderSupport(root,o);}catch(e){o.toast(e.message);b.disabled=false;}});};add(data.cases);
 let before=data.cases.at(-1); root.querySelector('#cases-more').hidden=data.cases.length<50;
 root.querySelector('#cases-more').onclick=async e=>{e.currentTarget.disabled=true;try{const page=await o.invoke('support',{action:'list',before});add(page.cases);before=page.cases.at(-1);root.querySelector('#cases-more').hidden=page.cases.length<50;}catch(e){o.toast(e.message);}finally{root.querySelector('#cases-more').disabled=false;}};
 root.querySelector('#support-report').onsubmit=async e=>{e.preventDefault();const b=e.submitter;b.disabled=true;try{const v=Object.fromEntries(new FormData(e.target));await o.invoke('support',{action:'report',...v,rentalId:v.rentalId||null,subjectId:new URLSearchParams(location.hash.split('?')[1]||'').get('subject'),requestId:crypto.randomUUID()});await renderSupport(root,o);}catch(e){root.querySelector('#case-status').textContent=e.message;b.disabled=false;}};
 }catch(e){if(root.isConnected)root.innerHTML=`<h1>Support</h1><p>${esc(e.message)}</p><button id="support-retry">Retry</button>`;root.querySelector('#support-retry')?.addEventListener('click',()=>renderSupport(root,o));}
}
