import {esc} from './core.js';
const time=value=>esc(new Date(value).toLocaleString());
export async function renderSupport(root,o){
 root.innerHTML='<h1>Support & notifications</h1><p>For an emergency, contact local emergency services. This queue is not emergency assistance.</p><p role="status">Loading…</p>';
 try{
  const data=await o.invoke('support',{action:'list'});if(!root.isConnected)return;
  root.innerHTML=`<h1>Support & notifications</h1><p>For an emergency, contact local emergency services. For rental or payment problems, open a case below. Case deadlines are targets, not a promise of immediate response.</p>${data.operatorEligible&&!data.operator?'<section class="panel operator-setup"><h2>Finish operator setup</h2><p>Your account is approved for operator access. Enable and verify an authenticator to open the operator queue and make audited decisions.</p><a class="button" href="#/profile?security=mfa">Set up operator two-factor authentication</a></section>':''}<h2>Notifications</h2><button id="notices-refresh">Refresh notifications</button><button id="notices-read">Mark displayed notifications read</button><div id="notices"></div><button id="notices-more">Load older notifications</button><form id="support-report" class="form-card"><h2>Open a case</h2><label>Rental reference (optional)<input name="rentalId" placeholder="Rental ID from your receipt"></label><label>Reason<select name="kind">${['payment','not_received','damage','safety','abuse','withdrawal','deletion'].map(k=>`<option value="${k}">${esc(k.replaceAll('_',' '))}</option>`).join('')}</select></label><label>What happened?<textarea name="description" minlength="10" maxlength="3000" required></textarea></label><button class="primary">Submit case</button><p role="status" id="case-status"></p></form><h2>${data.operator?'Operator queue':'Your cases'}</h2><div id="case-list"></div><button id="cases-more">Load older cases</button>${data.operator?'<section id="delivery-status" class="panel"></section>':''}`;
  const seen=new Map();let noticeBefore;
  const addNotices=rows=>{
   for(const n of rows){if(seen.has(String(n.id)))continue;seen.set(String(n.id),n);const el=document.createElement('article');el.className='notice'+(n.read_at?'':' unread');el.dataset.noticeId=n.id;el.innerHTML=`<p>${esc(n.message)}</p><p class="fine">${time(n.created_at)} <span class="notice-state">${n.read_at?'Read':'Unread'}</span></p>${n.rental_id?`<a href="#/rental/${esc(n.rental_id)}">Open rental</a>`:''}${n.read_at?'':`<button data-read="${esc(n.id)}">Mark read</button>`}`;root.querySelector('#notices').append(el);}
   if(!seen.size)root.querySelector('#notices').innerHTML='<p>No notifications.</p>';
   noticeBefore=rows.at(-1)?.id??noticeBefore;root.querySelector('#notices-more').hidden=rows.length<50;
   root.querySelector('#notices-read').disabled=![...seen.values()].some(n=>!n.read_at);
   root.querySelectorAll('[data-read]').forEach(button=>button.onclick=()=>markRead([button.dataset.read]));
  };
  const markRead=async ids=>{
   const buttons=[...root.querySelectorAll('#notices button,#notices-read')];buttons.forEach(b=>b.disabled=true);
   try{
    for(let i=0;i<ids.length;i+=50)await o.invoke('support',{action:'read-notifications',notificationIds:ids.slice(i,i+50)});
    for(const id of ids){const n=seen.get(String(id));if(n)n.read_at=new Date().toISOString();const el=root.querySelector(`[data-notice-id="${id}"]`);if(el){el.classList.remove('unread');el.querySelector('.notice-state').textContent='Read';el.querySelector('[data-read]')?.remove();}}
    await o.onRead?.();
   }catch(e){o.toast(e.message);}finally{buttons.forEach(b=>b.disabled=false);root.querySelector('#notices-read').disabled=![...seen.values()].some(n=>!n.read_at);}
  };
  addNotices(data.notifications);
  root.querySelector('#notices-read').onclick=()=>markRead([...seen.values()].filter(n=>!n.read_at).map(n=>String(n.id)));
  root.querySelector('#notices-refresh').onclick=async e=>{const button=e.currentTarget;button.disabled=true;try{const page=await o.invoke('support',{action:'notifications'});if(!root.isConnected)return;seen.clear();noticeBefore=undefined;root.querySelector('#notices').innerHTML='';addNotices(page.notifications);await o.onRead?.();}catch(error){o.toast(error.message);}finally{button.disabled=false;}};
  root.querySelector('#notices-more').onclick=async e=>{const button=e.currentTarget;button.disabled=true;try{const page=await o.invoke('support',{action:'notifications',beforeNotificationId:String(noticeBefore)});if(root.isConnected)addNotices(page.notifications);}catch(e){o.toast(e.message);}finally{button.disabled=false;}};
  const addCases=cases=>{
   for(const c of cases){const el=document.createElement('article');el.className='panel';el.innerHTML=`<h3>${esc(c.kind.replaceAll('_',' '))} · ${esc(c.status)}</h3><p>${esc(c.description)}</p><p>${esc(c.resolution)}</p><p class="fine">Case ${esc(c.id)} · target response ${time(c.due_at)}${c.assigned_to?' · Assigned':''}</p>${c.rental_id?`<a href="#/rental/${esc(c.rental_id)}">Rental reference</a>`:''}${data.operator?`<button data-evidence="${esc(c.id)}">View case evidence</button><div data-evidence-panel="${esc(c.id)}"></div><form data-case="${esc(c.id)}" class="stack"><label>Action<select name="operation"><option value="assign">Assign to me</option><option value="confirm-receipt">Confirm physical receipt</option><option value="settle-return">Settle return</option><option value="allocate-payment-loss">Allocate verified payment loss to owner earnings</option><option value="resolve">Resolve case / release case hold</option><option value="restrict-account">Restrict subject account</option><option value="restore-account">Restore subject account</option></select></label><label>Amount ($; agreed damage or verified payment loss allocation)<input name="amount" type="number" min="0" step="0.01" value="0"></label><label>Decision and supporting evidence<textarea name="note" minlength="10" maxlength="3000" required></textarea></label><button>Record audited decision</button></form>`:''}`;root.querySelector('#case-list').append(el);}
   root.querySelectorAll('[data-evidence]').forEach(b=>b.onclick=async()=>{b.disabled=true;try{const d=await o.invoke('support',{action:'details',caseId:b.dataset.evidence});const panel=root.querySelector(`[data-evidence-panel="${b.dataset.evidence}"]`);panel.innerHTML=`<pre class="case-evidence">${esc(JSON.stringify({rental:d.rental,verifiedPayments:d.receipts||[],decisions:d.audit||[]},null,2))}</pre>${d.photos.map(url=>`<a href="${esc(url)}" target="_blank" rel="noopener">Open condition evidence (expires in 5 minutes)</a>`).join('<br>')}`;}catch(e){o.toast(e.message);}finally{b.disabled=false;}});
   root.querySelectorAll('[data-case]').forEach(f=>f.onsubmit=async e=>{e.preventDefault();const b=e.submitter;b.disabled=true;try{const v=Object.fromEntries(new FormData(f));await o.invoke('support',{action:'operate',caseId:f.dataset.case,operation:v.operation,note:v.note,amountCents:Math.round(Number(v.amount)*100),requestId:(f.dataset.requestId ||= crypto.randomUUID())});await renderSupport(root,o);}catch(e){o.toast(e.message);b.disabled=false;}});
  };addCases(data.cases);
  let before=data.cases.at(-1);root.querySelector('#cases-more').hidden=data.cases.length<50;
  root.querySelector('#cases-more').onclick=async e=>{const button=e.currentTarget;button.disabled=true;try{const page=await o.invoke('support',{action:'list',before});if(!root.isConnected)return;addCases(page.cases);before=page.cases.at(-1);button.hidden=page.cases.length<50;}catch(e){o.toast(e.message);}finally{button.disabled=false;}};
  root.querySelector('#support-report').onsubmit=async e=>{e.preventDefault();const b=e.submitter;b.disabled=true;try{const v=Object.fromEntries(new FormData(e.target));await o.invoke('support',{action:'report',...v,rentalId:v.rentalId||null,subjectId:new URLSearchParams(location.hash.split('?')[1]||'').get('subject'),requestId:(e.target.dataset.requestId ||= crypto.randomUUID())});await renderSupport(root,o);}catch(e){root.querySelector('#case-status').textContent=e.message;b.disabled=false;}};
  if(data.operator&&data.deliveryStatus){const d=data.deliveryStatus;root.querySelector('#delivery-status').innerHTML=`<h2>Notification delivery</h2><p>${esc(d.pending)} pending · ${esc(d.failed)} need attention · ${esc(d.captured)} sandbox previews · ${esc(d.emailed)} emails sent</p><p>Sandbox previews stay here and send no email or SMS.</p>${(d.failedJobs||[]).map(j=>`<form data-retry-notice="${esc(j.notification_id)}" class="stack"><p>Notification ${esc(j.notification_id)} failed after ${esc(j.attempts)} attempts.</p><label>Reason for retry<textarea name="note" minlength="10" maxlength="1000" required></textarea></label><button>Retry notification delivery</button></form>`).join('')}${(d.previews||[]).map(p=>`<details><summary>Preview ${esc(p.notification_id)} · ${time(p.created_at)}</summary><p>${esc(p.subject)}</p><p>${esc(p.body)}</p></details>`).join('')}`;root.querySelectorAll('[data-retry-notice]').forEach(f=>f.onsubmit=async e=>{e.preventDefault();const b=e.submitter;b.disabled=true;try{await o.invoke('support',{action:'retry-notification',notificationId:f.dataset.retryNotice,note:String(new FormData(f).get('note')),requestId:(f.dataset.requestId ||= crypto.randomUUID())});await renderSupport(root,o);}catch(error){o.toast(error.message);b.disabled=false;}});}
 }catch(e){if(root.isConnected)root.innerHTML=`<h1>Support</h1><p>${esc(e.message)}</p><button id="support-retry">Retry</button>`;root.querySelector('#support-retry')?.addEventListener('click',()=>renderSupport(root,o));}
}
