import {money,esc} from './core.js';
export function amountInCents(value){
 const text=String(value).trim();if(!/^\d{1,6}(\.\d{1,2})?$/.test(text))throw Error('Enter a dollar amount with at most two decimal places.');
 const [whole,fraction='']=text.split('.'),cents=Number(whole)*100+Number(fraction.padEnd(2,'0'));if(!Number.isSafeInteger(cents)||cents<100)throw Error('Enter at least $1.');return cents;
}
const labels={stripe_funding:'Stripe credit purchase',funding_reversed:'Payment refund or dispute',funding_restored:'Payment dispute resolved',withdrawal_hold:'Credits reserved for Stripe transfer',rental_checkout:'Rental paid with credits',extension_checkout:'Extension paid with credits',owner_earnings:'Rental earnings',deposit_refund:'Deposit returned',rental_early_refund:'Unused rental time returned',checkout_released:'Checkout credits released',rental_cancelled:'Reservation refund'};
export function createWalletInterface(o){
 let openSequence=0;
 async function open(initial='funds',topupId=null){
  const sequence=++openSequence,account=o.state().user?.id;if(!account)return;
  o.showModal(`<div id="wallet-root"><div class="dialog-head"><h2>Tool Share Credits</h2><button data-close aria-label="Close credits">✕</button></div><p id="wallet-mode" class="fine">Checking payment mode…</p><div id="wallet-balance" class="wallet-summary" aria-live="polite">Loading verified balance…</div><div class="wallet-tabs" role="tablist" aria-label="Credit actions">${[['funds','Add funds'],['withdraw','Withdraw'],['activity','Activity']].map(([id,name])=>`<button role="tab" data-wallet-tab="${id}" aria-controls="wallet-${id==='withdraw'?'withdraw-panel':id}" aria-selected="false">${name}</button>`).join('')}</div><section id="wallet-funds" class="wallet-panel"><p>Add $1–$500 through Stripe Checkout. Paid credits can cover rentals and deposits. A pending payment adds no spendable credits.</p><form id="funds-form" class="stack"><label>Amount to add (USD)<input name="amount" type="number" min="1" max="500" step="0.01" value="25" required></label><button class="primary">Continue to Stripe</button></form><p id="funds-status" role="status"></p><h3>Funding receipts</h3><div id="funds-history"></div></section><section id="wallet-withdraw-panel" class="wallet-panel hidden"><p>Withdrawals transfer credits to your connected Stripe balance. Stripe pays out to the bank you configure in payout setup; bank arrival follows its settlement and payout schedule.</p><p class="fine">Stripe processing or payout fees may apply when money enters or leaves. Internal credit spending has no Stripe transaction fee. A separate transfer quote is shown before confirmation. Bank payout terms are shown in Stripe.</p>${o.state().profile?.stripe_onboarding_complete?'':'<p><a href="#/profile" id="wallet-setup-link">Finish Stripe payout setup in your profile</a> before withdrawing.</p>'}<form id="withdraw-form" class="stack"><label>Amount to withdraw (USD)<input name="amount" type="number" min="1" step="0.01" required></label><button class="primary">Request withdrawal</button></form><p id="withdraw-status" role="status"></p><div id="withdraw-history"></div></section><section id="wallet-activity" class="wallet-panel hidden"><p>Every credit movement is recorded once. The balance equals all credits received minus all credits spent or reserved for withdrawals.</p><button id="wallet-refresh">Refresh activity</button><p id="wallet-audit" class="fine"></p><div id="wallet-transactions"></div><button id="wallet-more" class="hidden">Load older transactions</button></section></div>`);
  const root=o.modal.querySelector('#wallet-root'),$=s=>root.querySelector(s),valid=()=>sequence===openSequence&&root.isConnected&&o.modal.open&&o.state().user?.id===account;
  const tab=name=>{for(const b of root.querySelectorAll('[data-wallet-tab]'))b.setAttribute('aria-selected',String(b.dataset.walletTab===name));for(const [key,id]of [['funds','wallet-funds'],['withdraw','wallet-withdraw-panel'],['activity','wallet-activity']])$('#'+id).classList.toggle('hidden',key!==name);};
  root.querySelectorAll('[data-wallet-tab]').forEach(b=>b.onclick=()=>tab(b.dataset.walletTab));tab(initial);
  $('#wallet-setup-link')?.addEventListener('click',o.closeModal);
  let options=null,summary=null,pendingFunding=null,withdrawId=crypto.randomUUID(),withdrawAmount=null,activity=null,entries=[];
  const draftKey='ng-funding-request:'+account;
  const readDraft=()=>{try{return JSON.parse(localStorage.getItem(draftKey)||'null')}catch{return null}};
  const clearDraft=()=>{try{localStorage.removeItem(draftKey)}catch{}};
  const setSummary=s=>{summary=s;$('#wallet-balance').innerHTML=`<b class="wallet-total">${money(s.balance_cents)} available</b><p class="fine">${money(s.total_in_cents)} received − ${money(s.total_out_cents)} spent or reserved · ${s.entry_count} ledger entries</p><p><b>${money(s.withdrawable_cents||0)} withdrawable</b> after settlement and the seven-day safety hold.</p>${s.pending_withdrawal_cents?`<p>${money(s.pending_withdrawal_cents)} reserved for a pending Stripe transfer.</p>`:''}${s.dispute_hold?'<p>Payment review required. Spending and new withdrawals are paused.</p>':''}`;$('#withdraw-form [name=amount]').max=String(Math.max(0,s.withdrawable_cents||0)/100);};
  async function loadActivity(older=false){
   const last=entries.at(-1),args=older?{p_anchor:activity.anchor,p_before_entry:last.entry_no}:{};
   const r=await o.supabase.rpc('wallet_activity',args);if(r.error)throw r.error;if(!valid())return;
   if(!older){activity=r.data;entries=[];}entries.push(...r.data.entries);
   $('#wallet-audit').textContent=`Verified at ${new Date(activity.as_of).toLocaleString()}: ${money(activity.total_in_cents)} in − ${money(activity.total_out_cents)} out = ${money(activity.balance_cents)}. Showing ${entries.length} of ${activity.entry_count} entries.`;
   $('#wallet-transactions').innerHTML=entries.map(e=>`<article class="wallet-entry"><div class="row"><b>${esc(labels[e.reason]||e.reason.replaceAll('_',' '))}</b><strong class="${e.amount_cents>0?'wallet-positive':'wallet-negative'}">${e.amount_cents>0?'+':''}${money(e.amount_cents)}</strong></div><small>${esc(new Date(e.created_at).toLocaleString())} · Balance after: ${money(e.running_balance_cents)}</small><small>Reference: ${esc(e.reference)}</small><small>Transaction #${e.entry_no} · Ledger ID: ${esc(e.id)}</small></article>`).join('')||'<p>No credit transactions yet.</p>';
   $('#wallet-more').classList.toggle('hidden',entries.length>=Number(activity.entry_count));
  }
  async function load(){
   const results=await Promise.all([o.supabase.rpc('wallet_summary'),o.supabase.from('credit_topups').select('id,amount_cents,processing_fee_cents,status,created_at,stripe_payment_intent_id,stripe_checkout_session_id,stripe_charge_id,available_at,refunded_cents,disputed_cents').order('created_at',{ascending:false}).limit(50),o.supabase.from('credit_withdrawals').select('id,amount_cents,status,created_at,stripe_transfer_id').order('created_at',{ascending:false}).limit(50)]);
   for(const r of results)if(r.error)throw r.error;if(!valid())return;
   setSummary(results[0].data);pendingFunding=results[1].data.find(t=>t.status==='pending_payment')||null;
   $('#funds-form button').disabled=Boolean(pendingFunding)||!options?.enabled;
   $('#funds-history').innerHTML=results[1].data.map(t=>`<article class="wallet-entry"><div class="row"><b>${money(t.amount_cents)} · ${esc(t.status==='paid'?'Payment verified':t.status.replaceAll('_',' '))}</b>${t.status==='pending_payment'?`<button data-topup-check="${t.id}">Check payment / resume</button><button data-topup-cancel="${t.id}">Cancel funding</button>`:''}</div><small>${esc(new Date(t.created_at).toLocaleString())} · Funding ID: ${t.id}</small><small>Processing fee: ${money(t.processing_fee_cents||0)} · Stripe total: ${money(t.amount_cents+(t.processing_fee_cents||0))}</small>${t.stripe_payment_intent_id?`<small>Stripe payment: ${esc(t.stripe_payment_intent_id)}</small>`:''}${t.available_at?`<small>Stripe settlement: ${esc(new Date(t.available_at).toLocaleString())}</small>`:''}${t.refunded_cents||t.disputed_cents?`<small>Reversed payment: ${money(Math.min(t.amount_cents,t.refunded_cents+t.disputed_cents))}</small>`:''}</article>`).join('')||'<p>No funding purchases yet.</p>';
   $('#withdraw-history').innerHTML=results[2].data.map(w=>`<article class="wallet-entry"><div class="row"><span>${money(w.amount_cents)} · ${esc(w.status==='paid'?'Sent to Stripe':'Pending / credits reserved')}</span>${w.status==='pending'?`<button data-withdraw-retry="${w.id}" data-amount="${w.amount_cents}">Retry same transfer</button>`:''}</div><small>${w.stripe_transfer_id?'Stripe transfer: '+esc(w.stripe_transfer_id):'Withdrawal ID: '+w.id}</small></article>`).join('')||'<p>No withdrawals yet.</p>';
   root.querySelectorAll('[data-topup-check]').forEach(b=>b.onclick=()=>fundingAction('status',b.dataset.topupCheck,b));
   root.querySelectorAll('[data-topup-cancel]').forEach(b=>b.onclick=()=>fundingAction('cancel',b.dataset.topupCancel,b));
   root.querySelectorAll('[data-withdraw-retry]').forEach(b=>b.onclick=()=>withdraw(Number(b.dataset.amount),b.dataset.withdrawRetry,b,true));
  }
  async function fundingAction(action,id,button){o.setBusy(button);try{const result=await o.invoke('credit-funding',{action,topupId:id});if(!valid())return;if(result.paid){clearDraft();$('#funds-status').textContent='Payment verified. Credits added once.';}else if(result.checkoutUrl&&action==='status'){location.assign(result.checkoutUrl);return;}else $('#funds-status').textContent=result.awaitingPayment?'Stripe is still confirming this payment. Credits appear after confirmation.':'Funding status: '+result.topup.status.replaceAll('_',' ');if(result.topup.status!=='pending_payment')clearDraft();await o.refresh({quiet:true});await load();await loadActivity();}catch(e){if(valid())$('#funds-status').textContent=e.message;}finally{if(valid())o.setBusy(button,false);}}
  async function withdraw(amount,id,button,retry=false){o.setBusy(button);try{const q=retry?{processingFeeCents:0}:await o.invoke('withdraw-credits',{action:'quote',amountCents:amount});if(!retry&&!confirm(`Credits debited: ${money(q.creditsDebitedCents)}\nTransfer processing fee: ${money(q.processingFeeCents)}\nSent to Stripe: ${money(q.stripeTransferCents)}\n${q.bankPayoutFee}\nContinue?`))return;await o.invoke('withdraw-credits',{amountCents:amount,requestId:id,confirmedFeeCents:q.processingFeeCents});if(!valid())return;$('#withdraw-status').textContent='Transferred to your Stripe balance. Bank arrival follows your Stripe payout schedule.';withdrawId=crypto.randomUUID();withdrawAmount=null;$('#withdraw-form').reset();await o.refresh({quiet:true});await load();await loadActivity();}catch(e){if(valid())$('#withdraw-status').textContent=e.message+' Retry the same transfer if credits are reserved.';}finally{if(valid())o.setBusy(button,false);}}
  $('#funds-form').onsubmit=async e=>{e.preventDefault();const b=e.submitter;o.setBusy(b);try{const amount=amountInCents(new FormData(e.target).get('amount'));if(amount>50000)throw Error('Maximum credit purchase is $500.');if(pendingFunding)throw Error('Resolve your pending funding payment first.');let draft=readDraft();if(draft&&draft.amount!==amount)throw Error('Retry the original amount until its funding request is resolved.');draft||={id:crypto.randomUUID(),amount};try{localStorage.setItem(draftKey,JSON.stringify(draft))}catch{}const q=await o.invoke('credit-funding',{action:'quote',amountCents:amount});if(!confirm(`Credits added: ${money(amount)}\nPayment processing fee: ${money(q.processingFeeCents)}\nTotal Stripe charge: ${money(q.totalCents)}\nContinue?`))return;const r=await o.invoke('credit-funding',{action:'create',confirmedFeeCents:q.processingFeeCents,requestId:draft.id,amountCents:amount,returnUrl:o.baseUrl()});if(!valid())return;if(r.checkoutUrl){location.assign(r.checkoutUrl);return;}if(r.topup.status!=='pending_payment')clearDraft();$('#funds-status').textContent=r.paid?'Payment verified. Credits added once.':'Funding status: '+r.topup.status.replaceAll('_',' ');await load();}catch(err){if(valid())$('#funds-status').textContent=err.message;}finally{if(valid())o.setBusy(b,false);}};
  $('#withdraw-form').onsubmit=async e=>{e.preventDefault();try{const amount=amountInCents(new FormData(e.target).get('amount'));if(amount>Number(summary?.withdrawable_cents||0))throw Error('Amount exceeds settled, withdrawable credits.');if(withdrawAmount!==null&&withdrawAmount!==amount)throw Error('Retry the original amount or the pending transfer shown below.');withdrawAmount=amount;await withdraw(amount,withdrawId,e.submitter);}catch(err){$('#withdraw-status').textContent=err.message;}};
  const historyAction=older=>async e=>{o.setBusy(e.currentTarget);try{await loadActivity(older);}catch(err){if(valid())$('#wallet-audit').textContent=err.message;}finally{if(valid())o.setBusy(e.currentTarget,false);}};
  $('#wallet-more').onclick=historyAction(true);$('#wallet-refresh').onclick=historyAction(false);
  try{options=await o.invoke('credit-funding',{action:'options'});if(!valid())return;$('#wallet-mode').textContent=options.sandbox?'Sandbox payments: test money only.':options.enabled?'Stripe payments enabled.':'Live credit funding awaits Stripe approval; existing credits remain available.';$('#withdraw-form button').textContent=options.sandbox?'Request sandbox withdrawal':'Request withdrawal';await load();await loadActivity();if(topupId&&valid())await fundingAction('status',topupId,$('#funds-form button'));}catch(err){if(valid()){$('#wallet-balance').textContent=err.message;$('#funds-form button').disabled=true;}}
 }
 return {open};
}
